/**
 * @typedef {{ range: string, name: string }} PaintEquivalent
 * @typedef {{ hex: string, equivalents: PaintEquivalent[] }} PaintEntry
 */

export const PAINT_RANGES = [
  "New Citadel",
  "Old Citadel",
  "Vallejo Game Color",
  "Vallejo Model Color",
  "INSTAR",
  "INSTAR Vintage",
  "Rackham",
  "Reaper Master",
  "Privateer Press P3",
  "Coat D'arms",
  "Army Painter",
  "Scale 75",
  "Two Thin Coats",
];

/** @type {PaintEntry[]} */
export const paintData = [
  {
    hex: "FFFFFF",
    equivalents: [
      { range: "New Citadel", name: "White Scar" },
      { range: "Old Citadel", name: "Skull White" },
      { range: "Vallejo Game Color", name: "Dead White (001)" },
      { range: "Vallejo Model Color", name: "White (951)" },
      { range: "INSTAR", name: "Arctic White" },
      { range: "Rackham", name: "Eternal White (1)" },
      { range: "Reaper Master", name: "Pure White (9039)" },
      { range: "Privateer Press P3", name: "Morrow White" },
      { range: "Coat D'arms", name: "White (101)" },
      { range: "Army Painter", name: "Matt White (WP1102)" },
      { range: "Scale 75", name: "White Matt" },
      { range: "Two Thin Coats", name: "White Star" },
    ],
  },
  {
    hex: "FFFFFF",
    equivalents: [
      { range: "New Citadel", name: "Ceramite White" },
      { range: "Old Citadel", name: "Smelly Primer" },
      { range: "Vallejo Game Color", name: "White Primer (002)" },
      { range: "Vallejo Model Color", name: "Foundation White (919)" },
      { range: "INSTAR", name: "Arctic White" },
      { range: "Reaper Master", name: "Brush-on Primer (9108)" },
      { range: "Privateer Press P3", name: "Morrow White" },
      { range: "Coat D'arms", name: "Grey Primer (141)" },
    ],
  },
  {
    hex: "EEC8C7",
    equivalents: [
      { range: "New Citadel", name: "Kislev Flesh" },
      { range: "Old Citadel", name: "Pallid Flesh" },
      { range: "Vallejo Game Color", name: "Pale Flesh (003)" },
      { range: "Vallejo Model Color", name: "Light Flesh (928)" },
      { range: "INSTAR", name: "Caramel" },
      { range: "Rackham", name: "Pearly Flesh (31)" },
      { range: "Reaper Master", name: "Rosy Highlight (9069)" },
      { range: "Privateer Press P3", name: "Ryn Flesh" },
      { range: "Coat D'arms", name: "Flesh (213)" },
      { range: "Army Painter", name: "Kobold Skin" },
      { range: "Scale 75", name: "Pale Skin Matt" },
      { range: "Two Thin Coats", name: "Elven Skin" },
    ],
  },
  {
    hex: "F7BD7B",
    equivalents: [
      { range: "New Citadel", name: "Bestigor Flesh" },
      { range: "Old Citadel", name: "Elf Flesh" },
      { range: "Vallejo Game Color", name: "Elf Skintone (004)" },
      { range: "Vallejo Model Color", name: "Flat Flesh (955)" },
      { range: "Rackham", name: "Craggy Skin (30)" },
      { range: "Reaper Master", name: "Rosy Highlight 2 (9069)" },
      { range: "Coat D'arms", name: "Elven Flesh (123)" },
    ],
  },
  {
    hex: "FFF700",
    equivalents: [
      { range: "New Citadel", name: "Dorn Yellow" },
      { range: "Old Citadel", name: "Bad Moon Yellow" },
      { range: "Vallejo Game Color", name: "Bad Moon Yellow (005)" },
      { range: "Vallejo Model Color", name: "Lemon Yellow (952)" },
      { range: "Reaper Master", name: "Clear Yellow (9095)" },
      { range: "Coat D'arms", name: "Dusky Yellow (146)" },
    ],
  },
  {
    hex: "FFE700",
    equivalents: [
      { range: "New Citadel", name: "Flash Gitz Yellow" },
      { range: "Old Citadel", name: "Sunburst Yellow" },
      { range: "Vallejo Game Color", name: "Sunblast Yellow (006)" },
      { range: "Vallejo Model Color", name: "Flat Yellow" },
      { range: "INSTAR", name: "Brilliant Yellow" },
      { range: "INSTAR Vintage", name: "IV-29" },
      { range: "Rackham", name: "Lahn Yellow (40)" },
      { range: "Reaper Master", name: "Sun Yellow (9008)" },
      { range: "Coat D'arms", name: "Sun Yellow (103)" },
      { range: "Army Painter", name: "Demonic Yellow (WP1107)" },
      { range: "Two Thin Coats", name: "Yellow Flame" },
    ],
  },
  {
    hex: "FFCE00",
    equivalents: [
      { range: "New Citadel", name: "Yriel Yellow" },
      { range: "Old Citadel", name: "Golden Yellow" },
      { range: "Vallejo Game Color", name: "Gold Yellow (007)" },
      { range: "Vallejo Model Color", name: "Golden Yellow (948)" },
      { range: "Rackham", name: "Royal Yellow (39)" },
      { range: "Reaper Master", name: "Marigold Yellow (9007)" },
      { range: "Privateer Press P3", name: "Heartfire" },
      { range: "Coat D'arms", name: "Golden Yellow (159)" },
      { range: "Two Thin Coats", name: "Skulker Yellow" },
    ],
  },
  {
    hex: "9C8855",
    equivalents: [
      { range: "New Citadel", name: "Tallarn Sand" },
      { range: "Old Citadel", name: "Desert Yellow" },
      { range: "Vallejo Game Color", name: "Desert Yellow (063)" },
      { range: "Vallejo Model Color", name: "Dark Yellow (978)" },
      { range: "INSTAR Vintage", name: "IV-30" },
      { range: "Reaper Master", name: "Faded Khaki (9129)" },
      { range: "Army Painter", name: "Desert Yellow (WP1121)" },
      { range: "Scale 75", name: "Sahara Yellow Matt" },
    ],
  },
  {
    hex: "EE3823",
    equivalents: [
      { range: "New Citadel", name: "Jokaero Orange" },
      { range: "Old Citadel", name: "Macharius Solar Orange" },
      { range: "Vallejo Game Color", name: "Heavy Orange (152)" },
      { range: "Vallejo Model Color", name: "German Orange (805)" },
      { range: "INSTAR", name: "Sunset Orange" },
      { range: "INSTAR Vintage", name: "IV-17" },
      { range: "Reaper Master", name: "Phoenix Red (9005)" },
    ],
  },
  {
    hex: "FF8552",
    equivalents: [
      { range: "New Citadel", name: "Fire Dragon Bright" },
      { range: "Old Citadel", name: "Fiery Orange" },
      { range: "Vallejo Game Color", name: "Orange Fire (008)" },
      { range: "Vallejo Model Color", name: "Light Orange (911)" },
      { range: "Rackham", name: "Merin's Fire (38)" },
      { range: "Reaper Master", name: "Fire Orange (9006)" },
      { range: "Coat D'arms", name: "Flame Orange (105)" },
      { range: "Army Painter", name: "Prison Jumpsuit (WP1211)" },
      { range: "Two Thin Coats", name: "Orange Flare" },
    ],
  },
  {
    hex: "F46C2E",
    equivalents: [
      { range: "New Citadel", name: "Troll Slayer Orange" },
      { range: "Old Citadel", name: "Blazing Orange" },
      { range: "Vallejo Game Color", name: "Hot Orange (009)" },
      { range: "Vallejo Model Color", name: "Scarlet (817)" },
      { range: "Rackham", name: "Fusion Red (37)" },
      { range: "Reaper Master", name: "Phoenix Red (9005)" },
      { range: "Coat D'arms", name: "Burnt Orange (147)" },
      { range: "Army Painter", name: "Mythical Orange (WP1442)" },
      { range: "Two Thin Coats", name: "Fanatic Orange" },
    ],
  },
  {
    hex: "991115",
    equivalents: [
      { range: "New Citadel", name: "Mephiston Red" },
      { range: "Old Citadel", name: "Mechrite Red" },
      { range: "Vallejo Game Color", name: "Heavy Red (141)" },
      { range: "Vallejo Model Color", name: "Red (926)" },
      { range: "INSTAR", name: "Crimson Red" },
      { range: "INSTAR Vintage", name: "IV-07" },
      { range: "Reaper Master", name: "Clotted Red (9134)" },
      { range: "Army Painter", name: "Vampire Red (WP1460)" },
      { range: "Two Thin Coats", name: "Sanguine Scarlet" },
    ],
  },
  {
    hex: "C21920",
    equivalents: [
      { range: "New Citadel", name: "Evil Sunz Scarlet" },
      { range: "Old Citadel", name: "Blood Red" },
      { range: "Vallejo Game Color", name: "Bloody Red (010)" },
      { range: "Vallejo Model Color", name: "Vermillion (909)" },
      { range: "INSTAR", name: "Burnt Red" },
      { range: "INSTAR Vintage", name: "IV-27" },
      { range: "Rackham", name: "Rackham Red (36)" },
      { range: "Reaper Master", name: "Clear Red (9094)" },
      { range: "Coat D'arms", name: "Blood Red (104)" },
      { range: "Army Painter", name: "Pure Red (WP1104)" },
      { range: "Scale 75", name: "Antares Red" },
      { range: "Two Thin Coats", name: "Demon Red" },
    ],
  },
  {
    hex: "EB2E28",
    equivalents: [
      { range: "New Citadel", name: "Wild Rider Red" },
      { range: "INSTAR", name: "Racing Red" },
      { range: "Army Painter", name: "Mars Red (WP1436)" },
    ],
  },
  {
    hex: "940008",
    equivalents: [
      { range: "New Citadel", name: "Wazdakka Red" },
      { range: "Old Citadel", name: "Red Gore" },
      { range: "Vallejo Game Color", name: "Gory Red (011)" },
      { range: "Vallejo Model Color", name: "Cavalry Brown (982)" },
      { range: "Rackham", name: "Natural Leather (34)" },
      { range: "Reaper Master", name: "Carnage Red (9135)" },
      { range: "Coat D'arms", name: "Vampire Red (129)" },
      { range: "Army Painter", name: "Dragon Red (WP1105)" },
      { range: "Scale 75", name: "Indian Shadow" },
      { range: "Two Thin Coats", name: "Evil Eye Red" },
    ],
  },
  {
    hex: "6A0002",
    equivalents: [
      { range: "New Citadel", name: "Khorne Red" },
      { range: "Old Citadel", name: "Scab Red" },
      { range: "Vallejo Game Color", name: "Scarlett Red (012)" },
      { range: "Vallejo Model Color", name: "Carmine Red (908)" },
      { range: "INSTAR", name: "Wine Red" },
      { range: "INSTAR Vintage", name: "IV-01" },
      { range: "Rackham", name: "Arcavia Red (35)" },
      { range: "Reaper Master", name: "Deep Red (9002)" },
      { range: "Army Painter", name: "Chaotic Red (WP1142)" },
      { range: "Scale 75", name: "Deep Red Matt" },
      { range: "Two Thin Coats", name: "Asmodeus Red" },
    ],
  },
  {
    hex: "620104",
    equivalents: [
      { range: "New Citadel", name: "Word Bearers Red" },
      { range: "Army Painter", name: "Chaotic Red" },
      { range: "Two Thin Coats", name: "Berserker Red" },
    ],
  },
  {
    hex: "EF9CB5",
    equivalents: [
      { range: "New Citadel", name: "Emperor's Children" },
      { range: "Old Citadel", name: "Tentacle Pink" },
      { range: "Vallejo Game Color", name: "Squid Pink (013)" },
      { range: "Vallejo Model Color", name: "Pink (958)" },
      { range: "INSTAR", name: "Dark Pink" },
      { range: "Rackham", name: "Friend Flesh (33)" },
      { range: "Reaper Master", name: "Pale Violet 2 (9027)" },
      { range: "Privateer Press P3", name: "Carnal Pink" },
      { range: "Coat D'arms", name: "Shocking Pink (144)" },
      { range: "Two Thin Coats", name: "Hot Pink" },
    ],
  },
  {
    hex: "9C004A",
    equivalents: [
      { range: "New Citadel", name: "Screamer Pink" },
      { range: "Old Citadel", name: "Warlock Purple" },
      { range: "Vallejo Game Color", name: "Warlord Purple (014)" },
      { range: "Vallejo Model Color", name: "Magenta (945)" },
      { range: "INSTAR", name: "Dark Maroon" },
      { range: "Rackham", name: "Celestial Pink (46)" },
      { range: "Reaper Master", name: "Pale Violet Red (9027)" },
      { range: "Privateer Press P3", name: "Murderous Magenta" },
      { range: "Coat D'arms", name: "Warlock Purple (157)" },
      { range: "Scale 75", name: "Fuchsia Matt" },
      { range: "Two Thin Coats", name: "Sword Hilt Burgundy" },
    ],
  },
  {
    hex: "451636",
    equivalents: [
      { range: "New Citadel", name: "Barak-Nar Burgundy" },
      { range: "Army Painter", name: "Crusted Sore" },
      { range: "Two Thin Coats", name: "Royal Cloak" },
    ],
  },
  {
    hex: "4B213C",
    equivalents: [
      { range: "New Citadel", name: "Gal Vorbak Red" },
      { range: "Army Painter", name: "Crusted Sore" },
      { range: "Two Thin Coats", name: "Dread Red" },
    ],
  },
  {
    hex: "5A005A",
    equivalents: [
      { range: "New Citadel", name: "Xereus Purple" },
      { range: "Old Citadel", name: "Liche Purple" },
      { range: "Vallejo Game Color", name: "Hexed Lichen (015)" },
      { range: "Vallejo Model Color", name: "Royal Purple (810)" },
      { range: "INSTAR Vintage", name: "IV-34" },
      { range: "Rackham", name: "Divine Purple (6)" },
      { range: "Reaper Master", name: "Clear Plum (9132)" },
      { range: "Privateer Press P3", name: "Beaten Purple" },
      { range: "Coat D'arms", name: "Poison Purple (118)" },
      { range: "Army Painter", name: "Alien Purple (WP1128)" },
    ],
  },
  {
    hex: "562F7E",
    equivalents: [
      { range: "New Citadel", name: "Naggaroth Night" },
      { range: "Old Citadel", name: "Imperial Purple" },
      { range: "Vallejo Game Color", name: "Royal Purple (016)" },
      { range: "Vallejo Model Color", name: "Royal Purple (810)" },
      { range: "INSTAR", name: "Dark Purple" },
      { range: "Reaper Master", name: "Deep Amethyst (9079)" },
      { range: "Coat D'arms", name: "Amethyst Purple (160)" },
    ],
  },
  {
    hex: "412A7A",
    equivalents: [
      { range: "Old Citadel", name: "Nauseating Blue" },
      { range: "Vallejo Game Color", name: "Sick Blue (017)" },
      { range: "Vallejo Model Color", name: "Violet 2 (960)" },
      { range: "Reaper Master", name: "Clear Purple (9099)" },
      { range: "Privateer Press P3", name: "Bad Bruise" },
      { range: "Coat D'arms", name: "Nauseous Blue (162)" },
    ],
  },
  {
    hex: "27357E",
    equivalents: [
      { range: "Old Citadel", name: "Storm Blue" },
      { range: "Vallejo Game Color", name: "Stormy Blue (018)" },
      { range: "Vallejo Model Color", name: "Blue (925)" },
      { range: "Rackham", name: "Migol Blue (5)" },
      { range: "Reaper Master", name: "Ritterlich Blue 2 (9115)" },
    ],
  },
  {
    hex: "000031",
    equivalents: [
      { range: "Old Citadel", name: "Midnight Blue" },
      { range: "Vallejo Game Color", name: "Night Blue (019)" },
      { range: "Vallejo Model Color", name: "Dark Sea Blue" },
      { range: "Rackham", name: "Abyssal Blue (3)" },
      { range: "Reaper Master", name: "Ultramarine Shadow (9187)" },
    ],
  },
  {
    hex: "08085A",
    equivalents: [
      { range: "New Citadel", name: "Kantor Blue" },
      { range: "Old Citadel", name: "Regal Blue" },
      { range: "Vallejo Game Color", name: "Imperial Blue (020)" },
      { range: "Vallejo Model Color", name: "Dark Prussian Blue" },
      { range: "INSTAR", name: "Marianas Blue" },
      { range: "Reaper Master", name: "Brilliant Blue (9116)" },
      { range: "Coat D'arms", name: "Royal Blue (110)" },
      { range: "Army Painter", name: "Deep Blue (WP1116)" },
      { range: "Two Thin Coats", name: "Abyss Blue" },
    ],
  },
  {
    hex: "29397B",
    equivalents: [
      { range: "New Citadel", name: "Altdorf Guard Blue" },
      { range: "Old Citadel", name: "Ultramarine Blue" },
      { range: "Vallejo Game Color", name: "Ultra Marine Blue (022)" },
      { range: "Vallejo Model Color", name: "Ultramarine (839)" },
      { range: "INSTAR Vintage", name: "IV-28" },
      { range: "Rackham", name: "Wizard Blue 2 (7)" },
      { range: "Reaper Master", name: "Ultramarine Highlight 2 (9189)" },
      { range: "Coat D'arms", name: "Marine Blue (148)" },
      { range: "Army Painter", name: "Ultramarine Blue (WP1115)" },
    ],
  },
  {
    hex: "2D567C",
    equivalents: [
      { range: "New Citadel", name: "Macragge Blue" },
      { range: "Old Citadel", name: "Mordian Blue" },
      { range: "Vallejo Game Color", name: "Heavy Blue (143)" },
      { range: "Vallejo Model Color", name: "Prussian Blue (965)" },
      { range: "INSTAR", name: "Deep Water Blue" },
      { range: "Reaper Master", name: "Breonne Blue (9055)" },
      { range: "Army Painter", name: "Dark Sky" },
      { range: "Scale 75", name: "Navy Blue Matt" },
      { range: "Two Thin Coats", name: "Marine Blue" },
    ],
  },
  {
    hex: "31639C",
    equivalents: [
      { range: "New Citadel", name: "Caledor Sky" },
      { range: "Old Citadel", name: "Enchanted Blue" },
      { range: "Vallejo Game Color", name: "Magic Blue (021)" },
      { range: "Vallejo Model Color", name: "Dark Blue (930)" },
      { range: "INSTAR", name: "Sapphire Blue" },
      { range: "Rackham", name: "Ephren Blue (4)" },
      { range: "Reaper Master", name: "Cyan Blue 2 (9117)" },
      { range: "Privateer Press P3", name: "Cygnar Blue Highlight" },
      { range: "Coat D'arms", name: "Wizard Blue (114)" },
      { range: "Army Painter", name: "Crystal Blue" },
      { range: "Two Thin Coats", name: "Witching Hour Blue" },
    ],
  },
  {
    hex: "4C78AF",
    equivalents: [
      { range: "New Citadel", name: "Hoeth Blue" },
      { range: "Army Painter", name: "Voidshield Blue" },
      { range: "Two Thin Coats", name: "Leviathan Blue" },
    ],
  },
  {
    hex: "6B9CCE",
    equivalents: [
      { range: "New Citadel", name: "Lothern Blue" },
      { range: "Old Citadel", name: "Ice Blue" },
      { range: "Vallejo Game Color", name: "Ice Blue (095)" },
      { range: "Vallejo Model Color", name: "Azure 2 (902)" },
      { range: "Rackham", name: "Glacier Blue (9)" },
      { range: "Army Painter", name: "Voidshield Blue (WP1452)" },
      { range: "Scale 75", name: "Sky Blue" },
    ],
  },
  {
    hex: "8BB9DD",
    equivalents: [
      { range: "New Citadel", name: "Teclis Blue" },
      { range: "Old Citadel", name: "Lightning Bolt Blue" },
      { range: "Vallejo Game Color", name: "Electric Blue (023)" },
      { range: "Vallejo Model Color", name: "Sky Blue (961)" },
      { range: "INSTAR", name: "Bright Blue" },
      { range: "Rackham", name: "Sacred Blue 2 (8)" },
      { range: "Reaper Master", name: "Sky Blue 2 (9018)" },
      { range: "Coat D'arms", name: "High Elf Blue (117)" },
      { range: "Army Painter", name: "Electric Blue (WP1113)" },
    ],
  },
  {
    hex: "00506F",
    equivalents: [
      { range: "New Citadel", name: "Thousand Sons Blue" },
      { range: "Army Painter", name: "Hydra Turquoise" },
      { range: "Two Thin Coats", name: "Sentient Turquoise" },
    ],
  },
  {
    hex: "00708A",
    equivalents: [
      { range: "New Citadel", name: "Ahriman Blue" },
      { range: "Army Painter", name: "Royal Cloak" },
      { range: "Two Thin Coats", name: "Cursed Blue" },
    ],
  },
  {
    hex: "006B5A",
    equivalents: [
      { range: "New Citadel", name: "Sotek Green" },
      { range: "Old Citadel", name: "Hawk Turquoise" },
      { range: "Vallejo Game Color", name: "Falcon Turquoise (024)" },
      { range: "Vallejo Model Color", name: "Light Turquoise (840)" },
      { range: "Rackham", name: "Precious Blue (12)" },
      { range: "Reaper Master", name: "Marine Teal (9077)" },
      { range: "Privateer Press P3", name: "Meredius Blue" },
      { range: "Coat D'arms", name: "Aquamarine (132)" },
      { range: "Army Painter", name: "Hydra Turquoise (WP1141)" },
      { range: "Scale 75", name: "Adriatic Blue Matt" },
    ],
  },
  {
    hex: "82C59C",
    equivalents: [
      { range: "New Citadel", name: "Sybarite Green" },
      { range: "Old Citadel", name: "Vile Green" },
      { range: "Vallejo Game Color", name: "Foul Green (025)" },
      { range: "Vallejo Model Color", name: "Park Green Flat (969)" },
      { range: "Rackham", name: "Antique Green (13)" },
      { range: "Two Thin Coats", name: "Ghoul Green" },
    ],
  },
  {
    hex: "069B7D",
    equivalents: [
      { range: "New Citadel", name: "Kabalite Green" },
      { range: "Old Citadel", name: "Jade Green" },
      { range: "Vallejo Game Color", name: "Jade Green (026)" },
      { range: "Vallejo Model Color", name: "Emerald (838)" },
      { range: "Reaper Master", name: "Reptilian Greens Triad 2 (9184/9185/9186)" },
      { range: "Privateer Press P3", name: "Eldritch" },
      { range: "Coat D'arms", name: "Jade Green 2 (158)" },
      { range: "Two Thin Coats", name: "Jade Green" },
    ],
  },
  {
    hex: "026B67",
    equivalents: [
      { range: "Old Citadel", name: "Scaly Green" },
      { range: "Vallejo Game Color", name: "Scurf/Scurvey Green (027)" },
      { range: "Vallejo Model Color", name: "Emerald (838)" },
      { range: "Rackham", name: "Chitin Green (19)" },
      { range: "Reaper Master", name: "Clear Viridian (9131)" },
    ],
  },
  {
    hex: "082E32",
    equivalents: [
      { range: "New Citadel", name: "Incubi Darkness" },
      { range: "Vallejo Model Color", name: "Dark Sea Blue (898)" },
      { range: "Two Thin Coats", name: "Hydra Green" },
    ],
  },
  {
    hex: "005221",
    equivalents: [
      { range: "New Citadel", name: "Caliban Green" },
      { range: "Old Citadel", name: "Dark Angels Green" },
      { range: "Vallejo Game Color", name: "Dark Green (028)" },
      { range: "Vallejo Model Color", name: "Deep Green (970)" },
      { range: "INSTAR", name: "Military Green" },
      { range: "INSTAR Vintage", name: "IV-15" },
      { range: "Rackham", name: "Diisha Green (18)" },
      { range: "Reaper Master", name: "Pine Green 2 (9010)" },
      { range: "Privateer Press P3", name: "Gnarls Green 2" },
      { range: "Coat D'arms", name: "Dark Elf Green (111)" },
      { range: "Army Painter", name: "Angel Green (WP1112)" },
      { range: "Two Thin Coats", name: "Wyvern Green" },
    ],
  },
  {
    hex: "106B21",
    equivalents: [
      { range: "New Citadel", name: "Warpstone Glow" },
      { range: "Old Citadel", name: "Snot Green" },
      { range: "Vallejo Game Color", name: "Sick Green (029)" },
      { range: "Vallejo Model Color", name: "Intermediate Green (891)" },
      { range: "INSTAR", name: "Grass Green" },
      { range: "Rackham", name: "Avagddu Green (17)" },
      { range: "Reaper Master", name: "Clear Green (9096)" },
      { range: "Privateer Press P3", name: "Ioson Green" },
      { range: "Coat D'arms", name: "Bogey Green (121)" },
      { range: "Scale 75", name: "Irati Green" },
      { range: "Two Thin Coats", name: "Emerald Green" },
    ],
  },
  {
    hex: "63B521",
    equivalents: [
      { range: "New Citadel", name: "Warboss Green" },
      { range: "Old Citadel", name: "Goblin Green" },
      { range: "Vallejo Game Color", name: "Goblin Green (030)" },
      { range: "Vallejo Model Color", name: "Pastel Green (885)" },
      { range: "INSTAR Vintage", name: "IV-13" },
      { range: "Rackham", name: "Chasm Green (16)" },
      { range: "Reaper Master", name: "Field Green 2 (9167)" },
      { range: "Coat D'arms", name: "Goblin Green (108)" },
      { range: "Army Painter", name: "Goblin Green (WP1109)" },
      { range: "Two Thin Coats", name: "Goblinoid Green" },
    ],
  },
  {
    hex: "A5A542",
    equivalents: [
      { range: "New Citadel", name: "Elysian Green" },
      { range: "Old Citadel", name: "Camo Green" },
      { range: "Vallejo Game Color", name: "Camouflage Green (031)" },
      { range: "Vallejo Model Color", name: "Olive Green (967)" },
      { range: "Reaper Master", name: "Camouflage Green 2 (9177)" },
      { range: "Scale 75", name: "Ardennes Green Matt" },
    ],
  },
  {
    hex: "A5D610",
    equivalents: [
      { range: "New Citadel", name: "Moot Green" },
      { range: "Old Citadel", name: "Scorpion Green" },
      { range: "Vallejo Game Color", name: "Scorpy Green (032)" },
      { range: "Vallejo Model Color", name: "Light Green (942)" },
      { range: "INSTAR", name: "Lime Green" },
      { range: "Rackham", name: "Quithayran Green (14)" },
      { range: "Reaper Master", name: "Pale Green (9012)" },
      { range: "Privateer Press P3", name: "Necrotite Green" },
      { range: "Coat D'arms", name: "Scorpion Green (152)" },
      { range: "Scale 75", name: "Spring Green" },
      { range: "Two Thin Coats", name: "Ethereal Green" },
    ],
  },
  {
    hex: "A9D171",
    equivalents: [
      { range: "Old Citadel", name: "Bilious Green" },
      { range: "Vallejo Game Color", name: "Livery Green (033)" },
      { range: "Vallejo Model Color", name: "Yellow Green 2 (954)" },
      { range: "Rackham", name: "Mystic Green (15)" },
      { range: "Reaper Master", name: "Spring Green 2 (9146)" },
    ],
  },
  {
    hex: "455440",
    equivalents: [
      { range: "New Citadel", name: "Castellan Green" },
      { range: "Old Citadel", name: "Catachan Green" },
      { range: "Vallejo Game Color", name: "Cayman Green (067)" },
      { range: "Vallejo Model Color", name: "Olive Grey (888)" },
      { range: "INSTAR", name: "Jungle Green" },
      { range: "Reaper Master", name: "Muddy Olive (9034)" },
      { range: "Scale 75", name: "Boreal Green Matt" },
      { range: "Two Thin Coats", name: "Fury Green" },
    ],
  },
  {
    hex: "384E49",
    equivalents: [
      { range: "New Citadel", name: "Waaagh! Flesh" },
      { range: "Old Citadel", name: "Orkhide Shade" },
      { range: "Vallejo Game Color", name: "Heavy Blackgreen (147)" },
      { range: "Vallejo Model Color", name: "Black Green (980)" },
      { range: "INSTAR", name: "Pine Green" },
      { range: "INSTAR Vintage", name: "IV-10" },
      { range: "Reaper Master", name: "Jungle Moss (9082)" },
      { range: "Scale 75", name: "Black" },
      { range: "Two Thin Coats", name: "Orc Hide" },
    ],
  },
  {
    hex: "434F38",
    equivalents: [
      { range: "New Citadel", name: "Loren Forest" },
      { range: "Old Citadel", name: "Knarloc Green" },
      { range: "Vallejo Game Color", name: "Heavy Green (146)" },
      { range: "Vallejo Model Color", name: "Luftwaffe Ca. Green (823)" },
      { range: "INSTAR Vintage", name: "IV-22" },
      { range: "Reaper Master", name: "Olive Drab (9158)" },
      { range: "Army Painter", name: "Army Green (WP1110)" },
      { range: "Two Thin Coats", name: "Gung-Ho Green" },
    ],
  },
  {
    hex: "5D6732",
    equivalents: [
      { range: "New Citadel", name: "Deathworld Forest" },
      { range: "Old Citadel", name: "Gretchin Green" },
      { range: "Vallejo Game Color", name: "Heavy Khaki (149)" },
      { range: "Vallejo Model Color", name: "Russian Uniform WW2 (70.924)" },
      { range: "INSTAR", name: "Savannah Green" },
      { range: "INSTAR Vintage", name: "IV-25" },
      { range: "Reaper Master", name: "Worn Olive (9159)" },
      { range: "Army Painter", name: "Venom Wyrm (WP1461)" },
    ],
  },
  {
    hex: "628026",
    equivalents: [
      { range: "New Citadel", name: "Straken Green" },
      { range: "Two Thin Coats", name: "Green Beret" },
    ],
  },
  {
    hex: "849B63",
    equivalents: [
      { range: "New Citadel", name: "Nurgling Green" },
      { range: "Old Citadel", name: "Rotting Flesh" },
      { range: "Vallejo Game Color", name: "Dead Flesh (035)" },
      { range: "Vallejo Model Color", name: "Green Sky" },
      { range: "Rackham", name: "Dead Flesh (11)" },
      { range: "Reaper Master", name: "Pale Olive (9036)" },
      { range: "Privateer Press P3", name: "Jack Bone" },
      { range: "Coat D'arms", name: "Putrid Green (125)" },
      { range: "Army Painter", name: "Necrotic Flesh" },
    ],
  },
  {
    hex: "EFD9A8",
    equivalents: [
      { range: "New Citadel", name: "Ushabti Bone" },
      { range: "Old Citadel", name: "Bleached Bone" },
      { range: "Vallejo Game Color", name: "Bonewhite (034)" },
      { range: "Vallejo Model Color", name: "Buff (976)" },
      { range: "INSTAR", name: "Dust Brown" },
      { range: "INSTAR Vintage", name: "IV-38" },
      { range: "Rackham", name: "Wildcat Gray 2 (42)" },
      { range: "Reaper Master", name: "Yellowed Bone (9143)" },
      { range: "Privateer Press P3", name: "Menoth White Base" },
      { range: "Coat D'arms", name: "Bone (112)" },
      { range: "Army Painter", name: "Skeleton Bone (WP1125)" },
      { range: "Scale 75", name: "Golden Skin Matt" },
      { range: "Two Thin Coats", name: "Skeleton Legion" },
    ],
  },
  {
    hex: "9E915C",
    equivalents: [
      { range: "New Citadel", name: "Zandri Dust" },
      { range: "Old Citadel", name: "Kommando Khaki" },
      { range: "Vallejo Game Color", name: "Khaki (061)" },
      { range: "Vallejo Model Color", name: "G. Cam. Beige (821)" },
      { range: "INSTAR", name: "Golden Brown" },
      { range: "Reaper Master", name: "Terran Khaki (9122)" },
      { range: "Scale 75", name: "Thar Brown Matt" },
      { range: "Two Thin Coats", name: "Dragon Fang" },
    ],
  },
  {
    hex: "CDCEBE",
    equivalents: [
      { range: "New Citadel", name: "Pallid Wych Flesh" },
      { range: "Two Thin Coats", name: "Ivory Tusk" },
    ],
  },
  {
    hex: "F0F1CE",
    equivalents: [
      { range: "New Citadel", name: "Screaming Skull" },
      { range: "Vallejo Model Color", name: "Ivory (918)" },
      { range: "Privateer Press P3", name: "Menoth White Highlight" },
      { range: "Scale 75", name: "White Sands Matt" },
      { range: "Two Thin Coats", name: "Vampire Fang" },
    ],
  },
  {
    hex: "F7944A",
    equivalents: [
      { range: "Old Citadel", name: "Bronzed Flesh" },
      { range: "Vallejo Game Color", name: "Bronze Flesh (036)" },
      { range: "Vallejo Model Color", name: "Dark Flesh (927)" },
      { range: "Reaper Master", name: "Burnt Orange 2 (9111)" },
      { range: "Coat D'arms", name: "Tanned Flesh (115)" },
    ],
  },
  {
    hex: "DE9408",
    equivalents: [
      { range: "New Citadel", name: "Tau Light Ochre" },
      { range: "Old Citadel", name: "Vomit Brown" },
      { range: "Vallejo Game Color", name: "Filthy Brown (037)" },
      { range: "Vallejo Model Color", name: "Beige Red 2" },
      { range: "INSTAR Vintage", name: "IV-11 / IV-12" },
      { range: "Rackham", name: "Tanned Skin (29)" },
      { range: "Reaper Master", name: "Tanned Leather (9031)" },
      { range: "Privateer Press P3", name: "Rucksack Tan" },
      { range: "Coat D'arms", name: "Bilious Brown (130)" },
      { range: "Two Thin Coats", name: "Manticore Ochre" },
    ],
  },
  {
    hex: "F78C5A",
    equivalents: [
      { range: "New Citadel", name: "Ratskin Flesh" },
      { range: "Old Citadel", name: "Dwarf Flesh" },
      { range: "Vallejo Game Color", name: "Dwarf Skin (041)" },
      { range: "Vallejo Model Color", name: "Brown Sand" },
      { range: "INSTAR", name: "Bronzed Flesh" },
      { range: "Reaper Master", name: "Rosy Skin (9068)" },
      { range: "Coat D'arms", name: "Dwarven Flesh (124)" },
      { range: "Army Painter", name: "Barbarian Flesh (WP1126)" },
    ],
  },
  {
    hex: "A95C3E",
    equivalents: [
      { range: "New Citadel", name: "Bugman's Glow" },
      { range: "Old Citadel", name: "Tanned Flesh" },
      { range: "Vallejo Game Color", name: "Tan (066)" },
      { range: "INSTAR", name: "Sunburnt Flesh" },
      { range: "Reaper Master", name: "Antique Rose (9139)" },
      { range: "Privateer Press P3", name: "Khardic Flesh" },
      { range: "Army Painter", name: "Tanned Flesh (WP1127)" },
      { range: "Scale 75", name: "Kalahari Orange Matt" },
      { range: "Two Thin Coats", name: "Barbarian Brawn" },
    ],
  },
  {
    hex: "D88E2D",
    equivalents: [
      { range: "Old Citadel", name: "Leprous Brown" },
      { range: "Vallejo Game Color", name: "Scrofulous Brown (038)" },
      { range: "Vallejo Model Color", name: "Gold Brown (877)" },
      { range: "Reaper Master", name: "Saffron Sunset 2 (9182)" },
      { range: "Coat D'arms", name: "Leprous Brown (156)" },
    ],
  },
  {
    hex: "C68400",
    equivalents: [
      { range: "New Citadel", name: "Zamesi Desert" },
      { range: "Old Citadel", name: "Bubonic Brown" },
      { range: "Vallejo Game Color", name: "Plague Brown (039)" },
      { range: "Vallejo Model Color", name: "Yellow Ochre (913)" },
      { range: "INSTAR", name: "Mustard Yellow" },
      { range: "INSTAR Vintage", name: "IV-32" },
      { range: "Rackham", name: "Forgotten Gold (25)" },
      { range: "Reaper Master", name: "Palomino Gold (9074)" },
      { range: "Privateer Press P3", name: "Moldy Ochre" },
      { range: "Coat D'arms", name: "Festering Brown (126)" },
      { range: "Scale 75", name: "Iroko Matt" },
    ],
  },
  {
    hex: "9C6B08",
    equivalents: [
      { range: "New Citadel", name: "Balor Brown" },
      { range: "Old Citadel", name: "Snakebite Leather" },
      { range: "Vallejo Game Color", name: "Cobra Leather / Leather Brown (040)" },
      { range: "Vallejo Model Color", name: "Brown Sand (876)" },
      { range: "INSTAR Vintage", name: "IV-31" },
      { range: "Rackham", name: "Kalliene Yellow (23)" },
      { range: "Reaper Master", name: "Chestnut Gold (9073)" },
      { range: "Coat D'arms", name: "Barbarian Leather (116)" },
    ],
  },
  {
    hex: "976F3C",
    equivalents: [
      { range: "New Citadel", name: "Balor Brown" },
      { range: "Old Citadel", name: "Tausept Ochre" },
      { range: "Vallejo Game Color", name: "Heavy Ochre (150)" },
      { range: "Vallejo Model Color", name: "Ochre Brown (856)" },
      { range: "INSTAR Vintage", name: "IV-21" },
      { range: "Reaper Master", name: "Half Orc Highlight (9204)" },
    ],
  },
  {
    hex: "843910",
    equivalents: [
      { range: "New Citadel", name: "Skrag Brown" },
      { range: "Old Citadel", name: "Vermin Brown" },
      { range: "Vallejo Game Color", name: "Parasite Brown (042)" },
      { range: "Vallejo Model Color", name: "Orange Brown (981)" },
      { range: "INSTAR Vintage", name: "IV-14" },
      { range: "Rackham", name: "Syhar Soil (24)" },
      { range: "Reaper Master", name: "Chestnut Brown 2 (9071)" },
      { range: "Coat D'arms", name: "Rat Brown (119)" },
      { range: "Scale 75", name: "Mars Orange Matt" },
      { range: "Two Thin Coats", name: "Dry Rust Brown" },
    ],
  },
  {
    hex: "390008",
    equivalents: [
      { range: "New Citadel", name: "Rhinox Hide" },
      { range: "Old Citadel", name: "Scorched Brown" },
      { range: "Vallejo Game Color", name: "Charred Brown (045)" },
      { range: "Vallejo Model Color", name: "Burnt Umber (941)" },
      { range: "INSTAR", name: "Chocolate Brown" },
      { range: "INSTAR Vintage", name: "IV-37" },
      { range: "Rackham", name: "Dirty Leather (20)" },
      { range: "Reaper Master", name: "Muddy Brown (9028)" },
      { range: "Privateer Press P3", name: "Umbral Umber" },
      { range: "Scale 75", name: "Black Leather Matt" },
      { range: "Two Thin Coats", name: "Cuirass Leather" },
    ],
  },
  {
    hex: "630808",
    equivalents: [
      { range: "New Citadel", name: "Doombull Brown" },
      { range: "Old Citadel", name: "Dark Flesh" },
      { range: "Vallejo Game Color", name: "Dark Fleshtone (044)" },
      { range: "Vallejo Model Color", name: "Mahogany Brown (846)" },
      { range: "Rackham", name: "Beastly Flesh (21)" },
      { range: "Reaper Master", name: "Chestnut Brown (9071)" },
      { range: "Two Thin Coats", name: "Boar Hide" },
    ],
  },
  {
    hex: "2B2A24",
    equivalents: [
      { range: "New Citadel", name: "Dryad Bark" },
      { range: "Army Painter", name: "Oak Brown" },
      { range: "Two Thin Coats", name: "Scorched Earth" },
    ],
  },
  {
    hex: "5F463F",
    equivalents: [
      { range: "New Citadel", name: "Gorthor Brown" },
      { range: "Army Painter", name: "Werewolf Fur" },
      { range: "Two Thin Coats", name: "Ancient Forest" },
    ],
  },
  {
    hex: "705E48",
    equivalents: [
      { range: "New Citadel", name: "Baneblade Brown" },
      { range: "Old Citadel", name: "Khemri Brown" },
      { range: "Vallejo Game Color", name: "Heavy Brown (153)" },
      { range: "Vallejo Model Color", name: "Green Brown" },
      { range: "INSTAR", name: "Bark Brown" },
      { range: "INSTAR Vintage", name: "IV-20" },
      { range: "Reaper Master", name: "Woodstain Brown (9160)" },
      { range: "Scale 75", name: "Arabic Shadow Matt" },
      { range: "Two Thin Coats", name: "Wasteland Brown" },
    ],
  },
  {
    hex: "663300",
    equivalents: [
      { range: "New Citadel", name: "Mournfang Brown" },
      { range: "Old Citadel", name: "Bestial Brown" },
      { range: "Vallejo Game Color", name: "Beasty Brown (043)" },
      { range: "Vallejo Model Color", name: "Flat Brown (984)" },
      { range: "INSTAR", name: "Red Brown" },
      { range: "Rackham", name: "Soil of Avagddu (22)" },
      { range: "Reaper Master", name: "Intense Brown (9138)" },
      { range: "Privateer Press P3", name: "Bloodtracker Brown" },
      { range: "Coat D'arms", name: "Hairy Brown (120)" },
      { range: "Two Thin Coats", name: "Noble Steed Brown" },
    ],
  },
  {
    hex: "6D5044",
    equivalents: [
      { range: "New Citadel", name: "Mournfang Brown" },
      { range: "Old Citadel", name: "Calthan Brown" },
      { range: "Vallejo Game Color", name: "Heavy Siena (154)" },
      { range: "Vallejo Model Color", name: "Flat Brown (984)" },
      { range: "INSTAR", name: "Red Brown" },
      { range: "INSTAR Vintage", name: "IV-03" },
      { range: "Reaper Master", name: "Dark Highlight (9042)" },
    ],
  },
  {
    hex: "793721",
    equivalents: [
      { range: "New Citadel", name: "XV-88" },
      { range: "Old Citadel", name: "Terracotta" },
      { range: "Vallejo Game Color", name: "Terracotta (065)" },
      { range: "INSTAR", name: "Sandstone Brown" },
      { range: "Reaper Master", name: "Clotted Red (9134)" },
      { range: "Two Thin Coats", name: "Gyzmo Fur" },
    ],
  },
  {
    hex: "655138",
    equivalents: [
      { range: "New Citadel", name: "Steel Legion Drab" },
      { range: "Old Citadel", name: "Graveyard Earth" },
      { range: "Vallejo Game Color", name: "Earth (062)" },
      { range: "Vallejo Model Color", name: "US Field Drab" },
      { range: "INSTAR", name: "Mud Brown" },
      { range: "INSTAR Vintage", name: "IV-36" },
      { range: "Reaper Master", name: "Uniform Brown (9127)" },
      { range: "Privateer Press P3", name: "Gun Corps Brown" },
      { range: "Army Painter", name: "Leather Brown (WP1123)" },
      { range: "Scale 75", name: "Gobi Brown Matt" },
      { range: "Two Thin Coats", name: "Dust Bowl" },
    ],
  },
  {
    hex: "9B8C7B",
    equivalents: [
      { range: "New Citadel", name: "Karak Stone" },
      { range: "Old Citadel", name: "Kommando Khaki" },
      { range: "Vallejo Game Color", name: "Khaki (061)" },
      { range: "Vallejo Model Color", name: "German Cam. Beige WWII (821)" },
      { range: "INSTAR", name: "Dirt Brown" },
      { range: "Reaper Master", name: "Terran Khaki (9122)" },
      { range: "Privateer Press P3", name: "Hammerfall Khaki" },
      { range: "Coat D'arms", name: "Horse Tone Roan (222)" },
      { range: "Two Thin Coats", name: "Temple Stone" },
    ],
  },
  {
    hex: "C3C6CD",
    equivalents: [
      { range: "New Citadel", name: "Ulthuan Grey" },
      { range: "Old Citadel", name: "Ghostly Grey" },
      { range: "Vallejo Game Color", name: "Ghost Grey (046)" },
      { range: "Vallejo Model Color", name: "Flat Aluminum (993)" },
      { range: "Reaper Master", name: "Ghost White (9063)" },
    ],
  },
  {
    hex: "CEDEE7",
    equivalents: [
      { range: "New Citadel", name: "Fenrisian Grey" },
      { range: "Old Citadel", name: "Space Wolves Grey" },
      { range: "Vallejo Game Color", name: "Wolf Grey (047)" },
      { range: "Vallejo Model Color", name: "Pale Greyblue (907)" },
      { range: "INSTAR", name: "Blue Steel" },
      { range: "INSTAR Vintage", name: "IV-05" },
      { range: "Reaper Master", name: "Snow Shadow (9021)" },
      { range: "Privateer Press P3", name: "Frostbite" },
      { range: "Coat D'arms", name: "Lupin Grey (151)" },
      { range: "Scale 75", name: "Bering Blue Matt" },
      { range: "Two Thin Coats", name: "Gravestone Blue" },
    ],
  },
  {
    hex: "4E5067",
    equivalents: [
      { range: "New Citadel", name: "The Fang" },
      { range: "Old Citadel", name: "Shadow Grey" },
      { range: "Vallejo Game Color", name: "Sombre Grey (048)" },
      { range: "Vallejo Model Color", name: "Oxford Blue (807)" },
      { range: "INSTAR", name: "Grey Blue" },
      { range: "INSTAR Vintage", name: "IV-04" },
      { range: "Reaper Master", name: "Twilight Blue (9020)" },
      { range: "Coat D'arms", name: "Shadow Grey (150)" },
      { range: "Army Painter", name: "Wolf Grey (WP1119)" },
      { range: "Two Thin Coats", name: "Cold Corpse Blue" },
    ],
  },
  {
    hex: "B5B5B5",
    equivalents: [
      { range: "New Citadel", name: "Administratum Grey" },
      { range: "Old Citadel", name: "Fortress Grey" },
      { range: "Vallejo Game Color", name: "Stonewall Grey (049)" },
      { range: "Vallejo Model Color", name: "Pale Grey Blue (907)" },
      { range: "INSTAR Vintage", name: "IV-35" },
      { range: "Rackham", name: "Sharp Gray (43)" },
      { range: "Reaper Master", name: "Weathered Stone (9087)" },
      { range: "Army Painter", name: "Ash Grey (WP1117)" },
      { range: "Scale 75", name: "Nacar Matt" },
      { range: "Two Thin Coats", name: "Carcharodon Grey" },
    ],
  },
  {
    hex: "999999",
    equivalents: [
      { range: "New Citadel", name: "Dawnstone" },
      { range: "Old Citadel", name: "Codex Grey" },
      { range: "Vallejo Game Color", name: "Cold Grey (050)" },
      { range: "Vallejo Model Color", name: "Basalt Grey (869)" },
      { range: "INSTAR", name: "Moon Grey" },
      { range: "Rackham", name: "Gray of Darkness (45)" },
      { range: "Reaper Master", name: "Rainy Grey (9038)" },
      { range: "Army Painter", name: "Uniform Grey (WP1118)" },
      { range: "Scale 75", name: "Artic Blue Matt" },
      { range: "Two Thin Coats", name: "Wizard Grey" },
    ],
  },
  {
    hex: "7C8286",
    equivalents: [
      { range: "New Citadel", name: "Mechanicus Standard Grey" },
      { range: "Old Citadel", name: "Adeptus Battlegrey" },
      { range: "Vallejo Game Color", name: "Heavy Grey 2" },
      { range: "Vallejo Model Color", name: "Russian Unif. (924)" },
      { range: "INSTAR", name: "Steel Grey" },
      { range: "INSTAR Vintage", name: "IV-18" },
      { range: "Reaper Master", name: "Military Green 2" },
      { range: "Privateer Press P3", name: "Great Coat Grey" },
      { range: "Scale 75", name: "Dungeon Stone Grey" },
    ],
  },
  {
    hex: "96A5A9",
    equivalents: [
      { range: "New Citadel", name: "Celestra Grey" },
      { range: "Old Citadel", name: "Astronomicon Grey" },
      { range: "Vallejo Game Color", name: "Heavy Bluegrey (144)" },
      { range: "Vallejo Model Color", name: "Pale Blue Grey (905)" },
      { range: "INSTAR", name: "Cool Grey" },
      { range: "INSTAR Vintage", name: "IV-24" },
      { range: "Reaper Master", name: "Weathered Stone (9087)" },
      { range: "Privateer Press P3", name: "Underbelly Blue" },
    ],
  },
  {
    hex: "000000",
    equivalents: [
      { range: "New Citadel", name: "Abaddon Black" },
      { range: "Old Citadel", name: "Chaos Black" },
      { range: "Vallejo Game Color", name: "Chaos Black / Black (051)" },
      { range: "Vallejo Model Color", name: "Black (950)" },
      { range: "INSTAR", name: "Obsidian Black" },
      { range: "Rackham", name: "Accursed Black (2)" },
      { range: "Reaper Master", name: "Pure Black (9037)" },
      { range: "Privateer Press P3", name: "Thamar Black" },
      { range: "Coat D'arms", name: "Black (102)" },
      { range: "Army Painter", name: "Matt Black (WP1101)" },
      { range: "Two Thin Coats", name: "Doom Death Black" },
    ],
  },
  {
    hex: "171314",
    equivalents: [
      { range: "New Citadel", name: "Corvus Black" },
      { range: "Army Painter", name: "Necromancer Cloak" },
      { range: "Two Thin Coats", name: "Death Reaper" },
    ],
  },
  {
    hex: "B5B5BD",
    equivalents: [
      { range: "New Citadel", name: "Runefang Steel" },
      { range: "Old Citadel", name: "Mithril Silver" },
      { range: "Vallejo Game Color", name: "Mithril Silver / Silver (052)" },
      { range: "Vallejo Model Color", name: "Silver (997)" },
      { range: "Rackham", name: "Polished Silver (49)" },
      { range: "Reaper Master", name: "Polished Silver (9054)" },
      { range: "Privateer Press P3", name: "Quicksilver" },
      { range: "Coat D'arms", name: "Enchanted Silver (106)" },
      { range: "Army Painter", name: "Shining Silver (WP1129)" },
    ],
  },
  {
    hex: "7B737B",
    equivalents: [
      { range: "New Citadel", name: "Ironbreaker" },
      { range: "Old Citadel", name: "Chainmail" },
      { range: "Vallejo Game Color", name: "Chain Mail (053)" },
      { range: "Vallejo Model Color", name: "Natural Steel (864)" },
      { range: "INSTAR", name: "Polished Steel" },
      { range: "Reaper Master", name: "Honed Steel (9053)" },
      { range: "Privateer Press P3", name: "Cold Steel" },
      { range: "Coat D'arms", name: "Chainmail (109)" },
      { range: "Army Painter", name: "Plate Mail Metal (WP1130)" },
    ],
  },
  {
    hex: "393939",
    equivalents: [
      { range: "New Citadel", name: "Leadbelcher" },
      { range: "Old Citadel", name: "Boltgun Metal" },
      { range: "Vallejo Game Color", name: "Gunmetal / Gunmetal Metal (054)" },
      { range: "Vallejo Model Color", name: "Gunmetal Grey (863)" },
      { range: "Reaper Master", name: "Shadowed Steel (9052)" },
      { range: "Privateer Press P3", name: "Pig Iron" },
      { range: "Coat D'arms", name: "Gun Metal (142)" },
      { range: "Army Painter", name: "Machinegun Metal (WP1221)" },
      { range: "Scale 75", name: "Petroleum Grey" },
      { range: "Two Thin Coats", name: "Sir Coates Silver" },
    ],
  },
  {
    hex: "E7BD42",
    equivalents: [
      { range: "New Citadel", name: "Auric Armour Gold" },
      { range: "Old Citadel", name: "Burnished Gold" },
      { range: "Vallejo Game Color", name: "Glorious Gold (056)" },
      { range: "Vallejo Model Color", name: "Gold (996)" },
      { range: "INSTAR", name: "Royal Gold" },
      { range: "Reaper Master", name: "Antique Gold (9050)" },
      { range: "Privateer Press P3", name: "Brass Balls 2" },
      { range: "Army Painter", name: "Bright Gold (WP1231)" },
      { range: "Scale 75", name: "Dwarven Gold" },
    ],
  },
  {
    hex: "CCCC33",
    equivalents: [
      { range: "New Citadel", name: "Gehenna's Gold" },
      { range: "Old Citadel", name: "Shining Gold" },
      { range: "Vallejo Game Color", name: "Polished Gold (055)" },
      { range: "Vallejo Model Color", name: "Old Gold (878)" },
      { range: "Reaper Master", name: "New Gold (9051)" },
      { range: "Privateer Press P3", name: "Solid Gold" },
      { range: "Coat D'arms", name: "Bright Gold (107)" },
      { range: "Army Painter", name: "Greedy Gold (WP1132)" },
      { range: "Scale 75", name: "Elven Gold" },
    ],
  },
  {
    hex: "9C5221",
    equivalents: [
      { range: "New Citadel", name: "Hashut Copper" },
      { range: "Old Citadel", name: "Dwarf Bronze" },
      { range: "Vallejo Game Color", name: "Bright Bronze (057)" },
      { range: "Vallejo Model Color", name: "Bronze (998)" },
      { range: "Reaper Master", name: "Ancient Bronze (9049)" },
      { range: "Privateer Press P3", name: "Molten Bronze" },
      { range: "Coat D'arms", name: "Dwarven Bronze (143)" },
      { range: "Army Painter", name: "Weapon Bronze (WP1133)" },
    ],
  },
  {
    hex: "735A21",
    equivalents: [
      { range: "New Citadel", name: "Runelord Brass" },
      { range: "Old Citadel", name: "Brazen Brass" },
      { range: "Vallejo Game Color", name: "Brassy Brass (058)" },
      { range: "Vallejo Model Color", name: "Brass (801)" },
      { range: "Reaper Master", name: "Tarnished Brass 2 (9198)" },
      { range: "Coat D'arms", name: "Brass (131)" },
      { range: "Scale 75", name: "Viking Gold" },
      { range: "Two Thin Coats", name: "Battle Axe Brass" },
    ],
  },
  {
    hex: "73372D",
    equivalents: [
      { range: "New Citadel", name: "Brass Scorpion" },
      { range: "Old Citadel", name: "Beaten Copper" },
      { range: "Vallejo Game Color", name: "Hammered Copper (059)" },
      { range: "Vallejo Model Color", name: "Copper (999)" },
      { range: "Reaper Master", name: "Coppery Orange (9102)" },
    ],
  },
  {
    hex: "393121",
    equivalents: [
      { range: "New Citadel", name: "Warplock Bronze" },
      { range: "Old Citadel", name: "Tin Bitz" },
      { range: "Vallejo Game Color", name: "Tinny Tin (060)" },
      { range: "Reaper Master", name: "Scorched Metal (9125)" },
      { range: "Privateer Press P3", name: "Deathless Metal" },
      { range: "Coat D'arms", name: "Magic Metal (113)" },
      { range: "Scale 75", name: "Necro Gold" },
    ],
  },
  {
    hex: "000000",
    equivalents: [
      { range: "Old Citadel", name: "Black Ink" },
      { range: "Vallejo Game Color", name: "Black Ink (94)" },
    ],
  },
  {
    hex: "108473",
    equivalents: [
      { range: "Old Citadel", name: "Dark Green Ink" },
      { range: "Vallejo Game Color", name: "Green Ink (89)" },
    ],
  },
  {
    hex: "CE8C42",
    equivalents: [
      { range: "Old Citadel", name: "Flesh Wash" },
      { range: "Coat D'arms", name: "Ink Wash - Flesh (133)" },
    ],
  },
  {
    hex: "513D3C",
    equivalents: [
      { range: "Old Citadel", name: "Magenta Ink" },
    ],
  },
  {
    hex: "842994",
    equivalents: [
      { range: "Old Citadel", name: "Purple Ink" },
      { range: "Vallejo Game Color", name: "Violet Ink (87)" },
    ],
  },
  {
    hex: "484B4E",
    equivalents: [
      { range: "New Citadel", name: "Eshin Grey" },
      { range: "Army Painter", name: "Necromancer Cloak" },
      { range: "Two Thin Coats", name: "Ashen Grey" },
    ],
  },
  {
    hex: "45413B",
    equivalents: [
      { range: "New Citadel", name: "Skavenblight Dinge" },
      { range: "Army Painter", name: "Hardened Carapace" },
      { range: "Two Thin Coats", name: "Eidolon Grey" },
    ],
  },
  {
    hex: "4D4A4A",
    equivalents: [
      { range: "New Citadel", name: "Stormvermin Fur" },
      { range: "Old Citadel", name: "Charadon Granite" },
      { range: "Vallejo Game Color", name: "Heavy Charcoal (155)" },
      { range: "Vallejo Model Color", name: "German Grey (995)" },
      { range: "INSTAR Vintage", name: "IV-02" },
      { range: "Reaper Master", name: "Pure Black (9103) 2" },
      { range: "Privateer Press P3", name: "Bastion Grey" },
      { range: "Scale 75", name: "Anthartic Grey Matt" },
      { range: "Two Thin Coats", name: "Rodent Grey" },
    ],
  },
  {
    hex: "B9ADA1",
    equivalents: [
      { range: "New Citadel", name: "Rakarth Flesh" },
      { range: "Old Citadel", name: "Dheneb Stone" },
      { range: "Vallejo Game Color", name: "Heavy Warmgrey 2 (148)" },
      { range: "INSTAR", name: "Pale Grey" },
      { range: "INSTAR Vintage", name: "IV-06" },
      { range: "Reaper Master", name: "Vampiric Shadow (9274)" },
      { range: "Army Painter", name: "Drake Tooth (WP1417)" },
      { range: "Two Thin Coats", name: "Griffon Claw" },
    ],
  },
  {
    hex: "4F566C",
    equivalents: [
      { range: "New Citadel", name: "Daemonette Hide" },
      { range: "Old Citadel", name: "Hormagaunt Purple" },
      { range: "Vallejo Game Color", name: "Heavy Violet (142)" },
      { range: "Vallejo Model Color", name: "Violet (960)" },
      { range: "INSTAR", name: "Light Purple" },
      { range: "INSTAR Vintage", name: "IV-26" },
      { range: "Reaper Master", name: "Nightshade Purple (9022)" },
      { range: "Scale 75", name: "Violet Blue Matt" },
    ],
  },
  {
    hex: "9C8A53",
    equivalents: [
      { range: "New Citadel", name: "Averland Sunset" },
      { range: "Old Citadel", name: "Iyanden Darksun" },
      { range: "Vallejo Game Color", name: "Heavy Goldbrown (151)" },
      { range: "Vallejo Model Color", name: "Goldbrown (877)" },
      { range: "INSTAR", name: "Warm Yellow" },
      { range: "INSTAR Vintage", name: "IV-16" },
      { range: "Reaper Master", name: "Green Ochre (9128)" },
      { range: "Privateer Press P3", name: "Sulferic Yellow" },
      { range: "Two Thin Coats", name: "Dark Sun Yellow" },
    ],
  },
  {
    hex: "8D736C",
    equivalents: [
      { range: "New Citadel", name: "Cadian Fleshtone" },
      { range: "Old Citadel", name: "Tallarn Flesh" },
      { range: "Vallejo Game Color", name: "Heavy Skintone (140)" },
      { range: "Vallejo Model Color", name: "Brown Rose" },
      { range: "INSTAR Vintage", name: "IV-19" },
      { range: "Reaper Master", name: "Leather Brown (9030)" },
      { range: "Two Thin Coats", name: "Dwarven Skin" },
    ],
  },
  // Washes
  {
    hex: "273E51",
    equivalents: [
      { range: "New Citadel", name: "Drakenhof Nightshade" },
      { range: "Old Citadel", name: "Asurmen Blue Wash" },
      { range: "Vallejo Game Color", name: "Blue Shade Wash (73207)" },
      { range: "INSTAR", name: "Blue" },
      { range: "INSTAR Vintage", name: "Blue" },
      { range: "Army Painter", name: "Blue Tone Ink (WP1139)" },
      { range: "Two Thin Coats", name: "Tempest Blue Wash" },
    ],
  },
  {
    hex: "630808",
    equivalents: [
      { range: "New Citadel", name: "Carroburg Crimson" },
      { range: "Old Citadel", name: "Baal Red Wash" },
      { range: "Vallejo Game Color", name: "Red Shade Wash (73206)" },
      { range: "INSTAR", name: "Red" },
      { range: "INSTAR Vintage", name: "Red" },
      { range: "Army Painter", name: "Red Tone Ink (WP1138)" },
      { range: "Two Thin Coats", name: "Hellion Red Wash" },
    ],
  },
  {
    hex: "000000",
    equivalents: [
      { range: "New Citadel", name: "Nuln Oil" },
      { range: "Old Citadel", name: "Badab Black Wash" },
      { range: "Vallejo Game Color", name: "Black Wash (73201)" },
      { range: "INSTAR", name: "Black" },
      { range: "INSTAR Vintage", name: "Black" },
      { range: "Reaper Master", name: "Armor Wash" },
      { range: "Army Painter", name: "Dark Tone Ink (WP1136)" },
      { range: "Two Thin Coats", name: "Oblivion Black Wash" },
    ],
  },
  {
    hex: "393121",
    equivalents: [
      { range: "New Citadel", name: "Agrax Earthshade" },
      { range: "Old Citadel", name: "Devlan Mud Wash" },
      { range: "Vallejo Game Color", name: "Umber Shade Wash (73203)" },
      { range: "INSTAR", name: "Brown" },
      { range: "INSTAR Vintage", name: "Brown" },
      { range: "Reaper Master", name: "Muddy Wash" },
      { range: "Army Painter", name: "Strong Tone Wash (WP1135)" },
      { range: "Two Thin Coats", name: "Battle Mud Wash" },
    ],
  },
  {
    hex: "843910",
    equivalents: [
      { range: "New Citadel", name: "Seraphim Sepia" },
      { range: "Old Citadel", name: "Gryphonne Sepia Wash" },
      { range: "Vallejo Game Color", name: "Sepia Wash (73200)" },
      { range: "Army Painter", name: "Soft Tone Ink (WP1134)" },
      { range: "Two Thin Coats", name: "Archaic Sepia Wash" },
    ],
  },
  {
    hex: "842994",
    equivalents: [
      { range: "New Citadel", name: "Druchii Violet" },
      { range: "Old Citadel", name: "Leviathan Purple Wash" },
      { range: "Vallejo Game Color", name: "Pale Grey Shade Wash (73202)" },
      { range: "INSTAR", name: "Purple" },
      { range: "Army Painter", name: "Purple Tone Ink (WP1140)" },
      { range: "Two Thin Coats", name: "Magi Purple Wash" },
    ],
  },
  {
    hex: "CE8C42",
    equivalents: [
      { range: "New Citadel", name: "Reikland Fleshshade" },
      { range: "Old Citadel", name: "Ogryn Flesh Wash" },
      { range: "Vallejo Game Color", name: "Fleshtone Shade Wash (73204)" },
      { range: "INSTAR", name: "Flesh" },
      { range: "Army Painter", name: "Flesh Wash (WP1143)" },
      { range: "Two Thin Coats", name: "Flesh Wash" },
    ],
  },
  {
    hex: "547757",
    equivalents: [
      { range: "New Citadel", name: "Biel-Tan Green" },
      { range: "Vallejo Game Color", name: "Green Wash" },
      { range: "Army Painter", name: "Green Tone Wash (WP1137)" },
      { range: "Two Thin Coats", name: "Orc Flesh Wash" },
    ],
  },
  {
    hex: "8B8B66",
    equivalents: [
      { range: "New Citadel", name: "Athonian Camoshade" },
      { range: "Army Painter", name: "Military Shade" },
      { range: "Two Thin Coats", name: "Necrosis Green Wash" },
    ],
  },
  // Edge paints
  {
    hex: "59C1CE",
    equivalents: [
      { range: "New Citadel", name: "Baharroth Blue (Edge)" },
      { range: "Privateer Press P3", name: "Arcane Blue" },
      { range: "Army Painter", name: "Toxic Mist (WP1437)" },
      { range: "Two Thin Coats", name: "Ray Gun Glow" },
    ],
  },
  {
    hex: "84C2A9",
    equivalents: [
      { range: "New Citadel", name: "Gauss Blaster Green (Edge)" },
    ],
  },
  {
    hex: "FFF685",
    equivalents: [
      { range: "New Citadel", name: "Dorn Yellow (Edge)" },
    ],
  },
  {
    hex: "F5AECC",
    equivalents: [
      { range: "New Citadel", name: "Fulgrim Pink (Edge)" },
      { range: "Scale 75", name: "Neo Pink" },
    ],
  },
  {
    hex: "CDC586",
    equivalents: [
      { range: "New Citadel", name: "Flayed One Flesh (Edge)" },
    ],
  },
  {
    hex: "B69FCD",
    equivalents: [
      { range: "New Citadel", name: "Dechala Lilac (Edge)" },
      { range: "Army Painter", name: "Oozing Purple (WP1445)" },
    ],
  },
  {
    hex: "BFBD82",
    equivalents: [
      { range: "New Citadel", name: "Kreig Khaki (Edge)" },
      { range: "Army Painter", name: "Necrotic Flesh (WP1108)" },
      { range: "Two Thin Coats", name: "Kobold Grey" },
    ],
  },
  {
    hex: "A4BAD2",
    equivalents: [
      { range: "New Citadel", name: "Blue Horror (Edge)" },
      { range: "Army Painter", name: "Gorgon Hide (WP1428)" },
      { range: "Two Thin Coats", name: "Celestial Blue" },
    ],
  },
  {
    hex: "F89E86",
    equivalents: [
      { range: "New Citadel", name: "Lugganath Orange (Edge)" },
      { range: "Army Painter", name: "Centaur Skin (WP1408)" },
    ],
  },
];

/**
 * Search paints by name
 * @param {string} query
 * @returns {PaintEntry[]}
 */
export function searchPaints(query) {
  if (!query || query.trim().length === 0) return [];
  const normalizedQuery = query.toLowerCase().trim();
  return paintData.filter((entry) =>
    entry.equivalents.some((eq) =>
      eq.name.toLowerCase().includes(normalizedQuery)
    )
  );
}
