/**
 * Flat paint database. Each paint has its own hex value.
 * Equivalents are computed at search time using Delta E color distance.
 *
 * Hex sources:
 *   - Citadel, Vallejo Game/Model, Army Painter, P3: RedGrimm paint-conversion
 *   - All other ranges: DakkaDakka wiki (approximate)
 *
 * Total: 840 paints across 13 ranges
 *
 * @typedef {{ range: string, name: string, hex: string }} Paint
 */

export const PAINT_RANGES = [
  "Army Painter",
  "Coat D'arms",
  "INSTAR",
  "INSTAR Vintage",
  "New Citadel",
  "Old Citadel",
  "Privateer Press P3",
  "Rackham",
  "Reaper Master",
  "Scale 75",
  "Two Thin Coats",
  "Vallejo Game Color",
  "Vallejo Model Color"
];

/** @type {Paint[]} */
export const paintData = [
  { range: "Army Painter", name: "Alien Purple (WP1128)", hex: "50317B" },
  { range: "Army Painter", name: "Angel Green (WP1112)", hex: "0C391D" },
  { range: "Army Painter", name: "Army Green (WP1110)", hex: "6E7645" },
  { range: "Army Painter", name: "Ash Grey (WP1117)", hex: "A2A5A4" },
  { range: "Army Painter", name: "Barbarian Flesh (WP1126)", hex: "E89C6C" },
  { range: "Army Painter", name: "Blue Tone Ink (WP1139)", hex: "273E51" },
  { range: "Army Painter", name: "Bright Gold (WP1231)", hex: "E7BD42" },
  { range: "Army Painter", name: "Centaur Skin (WP1408)", hex: "DEABA0" },
  { range: "Army Painter", name: "Chaotic Red", hex: "6C1E10" },
  { range: "Army Painter", name: "Chaotic Red (WP1142)", hex: "6C1E10" },
  { range: "Army Painter", name: "Crusted Sore", hex: "611624" },
  { range: "Army Painter", name: "Crystal Blue", hex: "0083C2" },
  { range: "Army Painter", name: "Dark Sky", hex: "2B4B5F" },
  { range: "Army Painter", name: "Dark Tone Ink (WP1136)", hex: "000000" },
  { range: "Army Painter", name: "Deep Blue (WP1116)", hex: "083251" },
  { range: "Army Painter", name: "Demonic Yellow (WP1107)", hex: "FFE700" },
  { range: "Army Painter", name: "Desert Yellow (WP1121)", hex: "C7952C" },
  { range: "Army Painter", name: "Dragon Red (WP1105)", hex: "9A1B1E" },
  { range: "Army Painter", name: "Drake Tooth (WP1417)", hex: "CFCBB4" },
  { range: "Army Painter", name: "Electric Blue (WP1113)", hex: "508CBE" },
  { range: "Army Painter", name: "Flesh Wash (WP1143)", hex: "CE8C42" },
  { range: "Army Painter", name: "Goblin Green (WP1109)", hex: "348941" },
  { range: "Army Painter", name: "Gorgon Hide (WP1428)", hex: "C7D2E4" },
  { range: "Army Painter", name: "Greedy Gold (WP1132)", hex: "CCCC33" },
  { range: "Army Painter", name: "Green Tone Wash (WP1137)", hex: "547757" },
  { range: "Army Painter", name: "Hardened Carapace", hex: "4C473F" },
  { range: "Army Painter", name: "Hydra Turquoise", hex: "199BA3" },
  { range: "Army Painter", name: "Hydra Turquoise (WP1141)", hex: "199BA3" },
  { range: "Army Painter", name: "Kobold Skin", hex: "C9A484" },
  { range: "Army Painter", name: "Leather Brown (WP1123)", hex: "764823" },
  { range: "Army Painter", name: "Machinegun Metal (WP1221)", hex: "393939" },
  { range: "Army Painter", name: "Mars Red (WP1436)", hex: "B73B37" },
  { range: "Army Painter", name: "Matt Black (WP1101)", hex: "231F20" },
  { range: "Army Painter", name: "Matt White (WP1102)", hex: "FFFFFF" },
  { range: "Army Painter", name: "Military Shade", hex: "8B8B66" },
  { range: "Army Painter", name: "Mythical Orange (WP1442)", hex: "E73D24" },
  { range: "Army Painter", name: "Necromancer Cloak", hex: "171314" },
  { range: "Army Painter", name: "Necrotic Flesh", hex: "BFC292" },
  { range: "Army Painter", name: "Necrotic Flesh (WP1108)", hex: "BFC292" },
  { range: "Army Painter", name: "Oak Brown", hex: "432010" },
  { range: "Army Painter", name: "Oozing Purple (WP1445)", hex: "AA94B4" },
  { range: "Army Painter", name: "Plate Mail Metal (WP1130)", hex: "7B737B" },
  { range: "Army Painter", name: "Prison Jumpsuit (WP1211)", hex: "FF8552" },
  { range: "Army Painter", name: "Pure Red (WP1104)", hex: "CF2127" },
  { range: "Army Painter", name: "Purple Tone Ink (WP1140)", hex: "842994" },
  { range: "Army Painter", name: "Red Tone Ink (WP1138)", hex: "630808" },
  { range: "Army Painter", name: "Royal Cloak", hex: "15999C" },
  { range: "Army Painter", name: "Shining Silver (WP1129)", hex: "B5B5BD" },
  { range: "Army Painter", name: "Skeleton Bone (WP1125)", hex: "D3C89D" },
  { range: "Army Painter", name: "Soft Tone Ink (WP1134)", hex: "843910" },
  { range: "Army Painter", name: "Strong Tone Wash (WP1135)", hex: "393121" },
  { range: "Army Painter", name: "Tanned Flesh (WP1127)", hex: "BC745E" },
  { range: "Army Painter", name: "Toxic Mist (WP1437)", hex: "39C0C5" },
  { range: "Army Painter", name: "Ultramarine Blue (WP1115)", hex: "0F4E85" },
  { range: "Army Painter", name: "Uniform Grey (WP1118)", hex: "5E6A73" },
  { range: "Army Painter", name: "Vampire Red (WP1460)", hex: "981D34" },
  { range: "Army Painter", name: "Venom Wyrm (WP1461)", hex: "6A653E" },
  { range: "Army Painter", name: "Voidshield Blue", hex: "2CA2D9" },
  { range: "Army Painter", name: "Voidshield Blue (WP1452)", hex: "2CA2D9" },
  { range: "Army Painter", name: "Weapon Bronze (WP1133)", hex: "9C5221" },
  { range: "Army Painter", name: "Werewolf Fur", hex: "785E4E" },
  { range: "Army Painter", name: "Wolf Grey (WP1119)", hex: "5B8093" },
  { range: "Coat D'arms", name: "Amethyst Purple (160)", hex: "562F7E" },
  { range: "Coat D'arms", name: "Aquamarine (132)", hex: "006B5A" },
  { range: "Coat D'arms", name: "Barbarian Leather (116)", hex: "9C6B08" },
  { range: "Coat D'arms", name: "Bilious Brown (130)", hex: "DE9408" },
  { range: "Coat D'arms", name: "Black (102)", hex: "000000" },
  { range: "Coat D'arms", name: "Blood Red (104)", hex: "C21920" },
  { range: "Coat D'arms", name: "Bogey Green (121)", hex: "106B21" },
  { range: "Coat D'arms", name: "Bone (112)", hex: "EFD9A8" },
  { range: "Coat D'arms", name: "Brass (131)", hex: "735A21" },
  { range: "Coat D'arms", name: "Bright Gold (107)", hex: "CCCC33" },
  { range: "Coat D'arms", name: "Burnt Orange (147)", hex: "F46C2E" },
  { range: "Coat D'arms", name: "Chainmail (109)", hex: "7B737B" },
  { range: "Coat D'arms", name: "Dark Elf Green (111)", hex: "005221" },
  { range: "Coat D'arms", name: "Dusky Yellow (146)", hex: "FFF700" },
  { range: "Coat D'arms", name: "Dwarven Bronze (143)", hex: "9C5221" },
  { range: "Coat D'arms", name: "Dwarven Flesh (124)", hex: "F78C5A" },
  { range: "Coat D'arms", name: "Elven Flesh (123)", hex: "F7BD7B" },
  { range: "Coat D'arms", name: "Enchanted Silver (106)", hex: "B5B5BD" },
  { range: "Coat D'arms", name: "Festering Brown (126)", hex: "C68400" },
  { range: "Coat D'arms", name: "Flame Orange (105)", hex: "FF8552" },
  { range: "Coat D'arms", name: "Flesh (213)", hex: "EEC8C7" },
  { range: "Coat D'arms", name: "Goblin Green (108)", hex: "63B521" },
  { range: "Coat D'arms", name: "Golden Yellow (159)", hex: "FFCE00" },
  { range: "Coat D'arms", name: "Grey Primer (141)", hex: "FFFFFF" },
  { range: "Coat D'arms", name: "Gun Metal (142)", hex: "393939" },
  { range: "Coat D'arms", name: "Hairy Brown (120)", hex: "663300" },
  { range: "Coat D'arms", name: "High Elf Blue (117)", hex: "8BB9DD" },
  { range: "Coat D'arms", name: "Horse Tone Roan (222)", hex: "9B8C7B" },
  { range: "Coat D'arms", name: "Ink Wash - Flesh (133)", hex: "CE8C42" },
  { range: "Coat D'arms", name: "Jade Green 2 (158)", hex: "069B7D" },
  { range: "Coat D'arms", name: "Leprous Brown (156)", hex: "D88E2D" },
  { range: "Coat D'arms", name: "Lupin Grey (151)", hex: "CEDEE7" },
  { range: "Coat D'arms", name: "Magic Metal (113)", hex: "393121" },
  { range: "Coat D'arms", name: "Marine Blue (148)", hex: "29397B" },
  { range: "Coat D'arms", name: "Nauseous Blue (162)", hex: "412A7A" },
  { range: "Coat D'arms", name: "Poison Purple (118)", hex: "5A005A" },
  { range: "Coat D'arms", name: "Putrid Green (125)", hex: "849B63" },
  { range: "Coat D'arms", name: "Rat Brown (119)", hex: "843910" },
  { range: "Coat D'arms", name: "Royal Blue (110)", hex: "08085A" },
  { range: "Coat D'arms", name: "Scorpion Green (152)", hex: "A5D610" },
  { range: "Coat D'arms", name: "Shadow Grey (150)", hex: "4E5067" },
  { range: "Coat D'arms", name: "Shocking Pink (144)", hex: "EF9CB5" },
  { range: "Coat D'arms", name: "Sun Yellow (103)", hex: "FFE700" },
  { range: "Coat D'arms", name: "Tanned Flesh (115)", hex: "F7944A" },
  { range: "Coat D'arms", name: "Vampire Red (129)", hex: "940008" },
  { range: "Coat D'arms", name: "Warlock Purple (157)", hex: "9C004A" },
  { range: "Coat D'arms", name: "White (101)", hex: "FFFFFF" },
  { range: "Coat D'arms", name: "Wizard Blue (114)", hex: "31639C" },
  { range: "INSTAR", name: "Arctic White", hex: "FFFFFF" },
  { range: "INSTAR", name: "Bark Brown", hex: "705E48" },
  { range: "INSTAR", name: "Black", hex: "000000" },
  { range: "INSTAR", name: "Blue", hex: "273E51" },
  { range: "INSTAR", name: "Blue Steel", hex: "CEDEE7" },
  { range: "INSTAR", name: "Bright Blue", hex: "8BB9DD" },
  { range: "INSTAR", name: "Brilliant Yellow", hex: "FFE700" },
  { range: "INSTAR", name: "Bronzed Flesh", hex: "F78C5A" },
  { range: "INSTAR", name: "Brown", hex: "393121" },
  { range: "INSTAR", name: "Burnt Red", hex: "C21920" },
  { range: "INSTAR", name: "Caramel", hex: "EEC8C7" },
  { range: "INSTAR", name: "Chocolate Brown", hex: "390008" },
  { range: "INSTAR", name: "Cool Grey", hex: "96A5A9" },
  { range: "INSTAR", name: "Crimson Red", hex: "991115" },
  { range: "INSTAR", name: "Dark Maroon", hex: "9C004A" },
  { range: "INSTAR", name: "Dark Pink", hex: "EF9CB5" },
  { range: "INSTAR", name: "Dark Purple", hex: "562F7E" },
  { range: "INSTAR", name: "Deep Water Blue", hex: "2D567C" },
  { range: "INSTAR", name: "Dirt Brown", hex: "9B8C7B" },
  { range: "INSTAR", name: "Dust Brown", hex: "EFD9A8" },
  { range: "INSTAR", name: "Flesh", hex: "CE8C42" },
  { range: "INSTAR", name: "Golden Brown", hex: "9E915C" },
  { range: "INSTAR", name: "Grass Green", hex: "106B21" },
  { range: "INSTAR", name: "Grey Blue", hex: "4E5067" },
  { range: "INSTAR", name: "Jungle Green", hex: "455440" },
  { range: "INSTAR", name: "Light Purple", hex: "4F566C" },
  { range: "INSTAR", name: "Lime Green", hex: "A5D610" },
  { range: "INSTAR", name: "Marianas Blue", hex: "08085A" },
  { range: "INSTAR", name: "Military Green", hex: "005221" },
  { range: "INSTAR", name: "Moon Grey", hex: "999999" },
  { range: "INSTAR", name: "Mud Brown", hex: "655138" },
  { range: "INSTAR", name: "Mustard Yellow", hex: "C68400" },
  { range: "INSTAR", name: "Obsidian Black", hex: "000000" },
  { range: "INSTAR", name: "Pale Grey", hex: "B9ADA1" },
  { range: "INSTAR", name: "Pine Green", hex: "384E49" },
  { range: "INSTAR", name: "Polished Steel", hex: "7B737B" },
  { range: "INSTAR", name: "Purple", hex: "842994" },
  { range: "INSTAR", name: "Racing Red", hex: "EB2E28" },
  { range: "INSTAR", name: "Red", hex: "630808" },
  { range: "INSTAR", name: "Red Brown", hex: "663300" },
  { range: "INSTAR", name: "Royal Gold", hex: "E7BD42" },
  { range: "INSTAR", name: "Sandstone Brown", hex: "793721" },
  { range: "INSTAR", name: "Sapphire Blue", hex: "31639C" },
  { range: "INSTAR", name: "Savannah Green", hex: "5D6732" },
  { range: "INSTAR", name: "Steel Grey", hex: "7C8286" },
  { range: "INSTAR", name: "Sunburnt Flesh", hex: "A95C3E" },
  { range: "INSTAR", name: "Sunset Orange", hex: "EE3823" },
  { range: "INSTAR", name: "Warm Yellow", hex: "9C8A53" },
  { range: "INSTAR", name: "Wine Red", hex: "6A0002" },
  { range: "INSTAR Vintage", name: "Black", hex: "000000" },
  { range: "INSTAR Vintage", name: "Blue", hex: "273E51" },
  { range: "INSTAR Vintage", name: "Brown", hex: "393121" },
  { range: "INSTAR Vintage", name: "IV-01", hex: "6A0002" },
  { range: "INSTAR Vintage", name: "IV-02", hex: "4D4A4A" },
  { range: "INSTAR Vintage", name: "IV-03", hex: "6D5044" },
  { range: "INSTAR Vintage", name: "IV-04", hex: "4E5067" },
  { range: "INSTAR Vintage", name: "IV-05", hex: "CEDEE7" },
  { range: "INSTAR Vintage", name: "IV-06", hex: "B9ADA1" },
  { range: "INSTAR Vintage", name: "IV-07", hex: "991115" },
  { range: "INSTAR Vintage", name: "IV-10", hex: "384E49" },
  { range: "INSTAR Vintage", name: "IV-11 / IV-12", hex: "DE9408" },
  { range: "INSTAR Vintage", name: "IV-13", hex: "63B521" },
  { range: "INSTAR Vintage", name: "IV-14", hex: "843910" },
  { range: "INSTAR Vintage", name: "IV-15", hex: "005221" },
  { range: "INSTAR Vintage", name: "IV-16", hex: "9C8A53" },
  { range: "INSTAR Vintage", name: "IV-17", hex: "EE3823" },
  { range: "INSTAR Vintage", name: "IV-18", hex: "7C8286" },
  { range: "INSTAR Vintage", name: "IV-19", hex: "8D736C" },
  { range: "INSTAR Vintage", name: "IV-20", hex: "705E48" },
  { range: "INSTAR Vintage", name: "IV-21", hex: "976F3C" },
  { range: "INSTAR Vintage", name: "IV-22", hex: "434F38" },
  { range: "INSTAR Vintage", name: "IV-24", hex: "96A5A9" },
  { range: "INSTAR Vintage", name: "IV-25", hex: "5D6732" },
  { range: "INSTAR Vintage", name: "IV-26", hex: "4F566C" },
  { range: "INSTAR Vintage", name: "IV-27", hex: "C21920" },
  { range: "INSTAR Vintage", name: "IV-28", hex: "29397B" },
  { range: "INSTAR Vintage", name: "IV-29", hex: "FFE700" },
  { range: "INSTAR Vintage", name: "IV-30", hex: "9C8855" },
  { range: "INSTAR Vintage", name: "IV-31", hex: "9C6B08" },
  { range: "INSTAR Vintage", name: "IV-32", hex: "C68400" },
  { range: "INSTAR Vintage", name: "IV-34", hex: "5A005A" },
  { range: "INSTAR Vintage", name: "IV-35", hex: "B5B5B5" },
  { range: "INSTAR Vintage", name: "IV-36", hex: "655138" },
  { range: "INSTAR Vintage", name: "IV-37", hex: "390008" },
  { range: "INSTAR Vintage", name: "IV-38", hex: "EFD9A8" },
  { range: "INSTAR Vintage", name: "Red", hex: "630808" },
  { range: "New Citadel", name: "Abaddon Black", hex: "010100" },
  { range: "New Citadel", name: "Administratum Grey", hex: "9DA299" },
  { range: "New Citadel", name: "Agrax Earthshade", hex: "393121" },
  { range: "New Citadel", name: "Ahriman Blue", hex: "1F8C9C" },
  { range: "New Citadel", name: "Altdorf Guard Blue", hex: "274B9B" },
  { range: "New Citadel", name: "Athonian Camoshade", hex: "8B8B66" },
  { range: "New Citadel", name: "Auric Armour Gold", hex: "E7BD42" },
  { range: "New Citadel", name: "Averland Sunset", hex: "FBBA00" },
  { range: "New Citadel", name: "Baharroth Blue (Edge)", hex: "58C1CD" },
  { range: "New Citadel", name: "Balor Brown", hex: "915E02" },
  { range: "New Citadel", name: "Baneblade Brown", hex: "99826B" },
  { range: "New Citadel", name: "Barak-Nar Burgundy", hex: "451636" },
  { range: "New Citadel", name: "Bestigor Flesh", hex: "D38A57" },
  { range: "New Citadel", name: "Biel-Tan Green", hex: "547757" },
  { range: "New Citadel", name: "Blue Horror (Edge)", hex: "A2BAD2" },
  { range: "New Citadel", name: "Brass Scorpion", hex: "73372D" },
  { range: "New Citadel", name: "Bugman\'s Glow", hex: "8C5144" },
  { range: "New Citadel", name: "Cadian Fleshtone", hex: "CB7953" },
  { range: "New Citadel", name: "Caledor Sky", hex: "38689C" },
  { range: "New Citadel", name: "Caliban Green", hex: "003B1D" },
  { range: "New Citadel", name: "Carroburg Crimson", hex: "630808" },
  { range: "New Citadel", name: "Castellan Green", hex: "384D20" },
  { range: "New Citadel", name: "Celestra Grey", hex: "9CAEAE" },
  { range: "New Citadel", name: "Ceramite White", hex: "FFFFFF" },
  { range: "New Citadel", name: "Corvus Black", hex: "171314" },
  { range: "New Citadel", name: "Daemonette Hide", hex: "696685" },
  { range: "New Citadel", name: "Dawnstone", hex: "7B7E74" },
  { range: "New Citadel", name: "Deathworld Forest", hex: "666C2D" },
  { range: "New Citadel", name: "Dechala Lilac (Edge)", hex: "B69FCC" },
  { range: "New Citadel", name: "Doombull Brown", hex: "5E0605" },
  { range: "New Citadel", name: "Dorn Yellow", hex: "FFF200" },
  { range: "New Citadel", name: "Dorn Yellow (Edge)", hex: "FFF200" },
  { range: "New Citadel", name: "Drakenhof Nightshade", hex: "273E51" },
  { range: "New Citadel", name: "Druchii Violet", hex: "842994" },
  { range: "New Citadel", name: "Dryad Bark", hex: "3B342E" },
  { range: "New Citadel", name: "Elysian Green", hex: "81932E" },
  { range: "New Citadel", name: "Emperor\'s Children", hex: "BD3F75" },
  { range: "New Citadel", name: "Eshin Grey", hex: "535659" },
  { range: "New Citadel", name: "Evil Sunz Scarlet", hex: "C21920" },
  { range: "New Citadel", name: "Fenrisian Grey", hex: "789EBB" },
  { range: "New Citadel", name: "Fire Dragon Bright", hex: "F1844A" },
  { range: "New Citadel", name: "Flash Gitz Yellow", hex: "FFEE00" },
  { range: "New Citadel", name: "Flayed One Flesh (Edge)", hex: "F3CA8A" },
  { range: "New Citadel", name: "Fulgrim Pink (Edge)", hex: "F4AFCD" },
  { range: "New Citadel", name: "Gal Vorbak Red", hex: "4B213C" },
  { range: "New Citadel", name: "Gauss Blaster Green (Edge)", hex: "84C3AA" },
  { range: "New Citadel", name: "Gehenna\'s Gold", hex: "CCCC33" },
  { range: "New Citadel", name: "Gorthor Brown", hex: "6E4E46" },
  { range: "New Citadel", name: "Hashut Copper", hex: "9C5221" },
  { range: "New Citadel", name: "Hoeth Blue", hex: "4F7FB5" },
  { range: "New Citadel", name: "Incubi Darkness", hex: "094345" },
  { range: "New Citadel", name: "Ironbreaker", hex: "7B737B" },
  { range: "New Citadel", name: "Jokaero Orange", hex: "E6200F" },
  { range: "New Citadel", name: "Kabalite Green", hex: "008660" },
  { range: "New Citadel", name: "Kantor Blue", hex: "06234F" },
  { range: "New Citadel", name: "Karak Stone", hex: "C1A069" },
  { range: "New Citadel", name: "Khorne Red", hex: "6A0A01" },
  { range: "New Citadel", name: "Kislev Flesh", hex: "DBAD75" },
  { range: "New Citadel", name: "Kreig Khaki (Edge)", hex: "BFBD82" },
  { range: "New Citadel", name: "Leadbelcher", hex: "393939" },
  { range: "New Citadel", name: "Loren Forest", hex: "5B7426" },
  { range: "New Citadel", name: "Lothern Blue", hex: "3BA1D1" },
  { range: "New Citadel", name: "Lugganath Orange (Edge)", hex: "F79E86" },
  { range: "New Citadel", name: "Macragge Blue", hex: "14397A" },
  { range: "New Citadel", name: "Mechanicus Standard Grey", hex: "454E50" },
  { range: "New Citadel", name: "Mephiston Red", hex: "9B0E05" },
  { range: "New Citadel", name: "Moot Green", hex: "57AA2D" },
  { range: "New Citadel", name: "Mournfang Brown", hex: "681104" },
  { range: "New Citadel", name: "Naggaroth Night", hex: "433656" },
  { range: "New Citadel", name: "Nuln Oil", hex: "000000" },
  { range: "New Citadel", name: "Nurgling Green", hex: "90A15F" },
  { range: "New Citadel", name: "Pallid Wych Flesh", hex: "D6D5C4" },
  { range: "New Citadel", name: "Rakarth Flesh", hex: "ABA495" },
  { range: "New Citadel", name: "Ratskin Flesh", hex: "AD6B4C" },
  { range: "New Citadel", name: "Reikland Fleshshade", hex: "CE8C42" },
  { range: "New Citadel", name: "Rhinox Hide", hex: "4E3433" },
  { range: "New Citadel", name: "Runefang Steel", hex: "B5B5BD" },
  { range: "New Citadel", name: "Runelord Brass", hex: "735A21" },
  { range: "New Citadel", name: "Screamer Pink", hex: "831740" },
  { range: "New Citadel", name: "Screaming Skull", hex: "D9D8A6" },
  { range: "New Citadel", name: "Seraphim Sepia", hex: "843910" },
  { range: "New Citadel", name: "Skavenblight Dinge", hex: "4F4840" },
  { range: "New Citadel", name: "Skrag Brown", hex: "954B00" },
  { range: "New Citadel", name: "Sotek Green", hex: "056976" },
  { range: "New Citadel", name: "Steel Legion Drab", hex: "695634" },
  { range: "New Citadel", name: "Stormvermin Fur", hex: "7D736A" },
  { range: "New Citadel", name: "Straken Green", hex: "6E8611" },
  { range: "New Citadel", name: "Sybarite Green", hex: "36A062" },
  { range: "New Citadel", name: "Tallarn Sand", hex: "AB7D00" },
  { range: "New Citadel", name: "Tau Light Ochre", hex: "C26E02" },
  { range: "New Citadel", name: "Teclis Blue", hex: "387BBF" },
  { range: "New Citadel", name: "The Fang", hex: "457479" },
  { range: "New Citadel", name: "Thousand Sons Blue", hex: "18ABCC" },
  { range: "New Citadel", name: "Troll Slayer Orange", hex: "EB641B" },
  { range: "New Citadel", name: "Ulthuan Grey", hex: "D2E4DF" },
  { range: "New Citadel", name: "Ushabti Bone", hex: "C6C180" },
  { range: "New Citadel", name: "Waaagh! Flesh", hex: "275627" },
  { range: "New Citadel", name: "Warboss Green", hex: "3B7D54" },
  { range: "New Citadel", name: "Warplock Bronze", hex: "393121" },
  { range: "New Citadel", name: "Warpstone Glow", hex: "257326" },
  { range: "New Citadel", name: "Wazdakka Red", hex: "8D0D01" },
  { range: "New Citadel", name: "White Scar", hex: "FFFFFF" },
  { range: "New Citadel", name: "Wild Rider Red", hex: "E21516" },
  { range: "New Citadel", name: "Word Bearers Red", hex: "620104" },
  { range: "New Citadel", name: "XV-88", hex: "7B4D1C" },
  { range: "New Citadel", name: "Xereus Purple", hex: "4B205C" },
  { range: "New Citadel", name: "Yriel Yellow", hex: "FFDA00" },
  { range: "New Citadel", name: "Zamesi Desert", hex: "E0A503" },
  { range: "New Citadel", name: "Zandri Dust", hex: "A89758" },
  { range: "Old Citadel", name: "Adeptus Battlegrey", hex: "7C8286" },
  { range: "Old Citadel", name: "Astronomicon Grey", hex: "96A5A9" },
  { range: "Old Citadel", name: "Asurmen Blue Wash", hex: "273E51" },
  { range: "Old Citadel", name: "Baal Red Wash", hex: "630808" },
  { range: "Old Citadel", name: "Bad Moon Yellow", hex: "FFF700" },
  { range: "Old Citadel", name: "Badab Black Wash", hex: "000000" },
  { range: "Old Citadel", name: "Beaten Copper", hex: "73372D" },
  { range: "Old Citadel", name: "Bestial Brown", hex: "663300" },
  { range: "Old Citadel", name: "Bilious Green", hex: "A9D171" },
  { range: "Old Citadel", name: "Black Ink", hex: "000000" },
  { range: "Old Citadel", name: "Blazing Orange", hex: "F46C2E" },
  { range: "Old Citadel", name: "Bleached Bone", hex: "EFD9A8" },
  { range: "Old Citadel", name: "Blood Red", hex: "C21920" },
  { range: "Old Citadel", name: "Boltgun Metal", hex: "393939" },
  { range: "Old Citadel", name: "Brazen Brass", hex: "735A21" },
  { range: "Old Citadel", name: "Bronzed Flesh", hex: "F7944A" },
  { range: "Old Citadel", name: "Bubonic Brown", hex: "C68400" },
  { range: "Old Citadel", name: "Burnished Gold", hex: "E7BD42" },
  { range: "Old Citadel", name: "Calthan Brown", hex: "6D5044" },
  { range: "Old Citadel", name: "Camo Green", hex: "A5A542" },
  { range: "Old Citadel", name: "Catachan Green", hex: "455440" },
  { range: "Old Citadel", name: "Chainmail", hex: "7B737B" },
  { range: "Old Citadel", name: "Chaos Black", hex: "000000" },
  { range: "Old Citadel", name: "Charadon Granite", hex: "4D4A4A" },
  { range: "Old Citadel", name: "Codex Grey", hex: "999999" },
  { range: "Old Citadel", name: "Dark Angels Green", hex: "005221" },
  { range: "Old Citadel", name: "Dark Flesh", hex: "630808" },
  { range: "Old Citadel", name: "Dark Green Ink", hex: "108473" },
  { range: "Old Citadel", name: "Desert Yellow", hex: "9C8855" },
  { range: "Old Citadel", name: "Devlan Mud Wash", hex: "393121" },
  { range: "Old Citadel", name: "Dheneb Stone", hex: "B9ADA1" },
  { range: "Old Citadel", name: "Dwarf Bronze", hex: "9C5221" },
  { range: "Old Citadel", name: "Dwarf Flesh", hex: "F78C5A" },
  { range: "Old Citadel", name: "Elf Flesh", hex: "F7BD7B" },
  { range: "Old Citadel", name: "Enchanted Blue", hex: "31639C" },
  { range: "Old Citadel", name: "Fiery Orange", hex: "FF8552" },
  { range: "Old Citadel", name: "Flesh Wash", hex: "CE8C42" },
  { range: "Old Citadel", name: "Fortress Grey", hex: "B5B5B5" },
  { range: "Old Citadel", name: "Ghostly Grey", hex: "C3C6CD" },
  { range: "Old Citadel", name: "Goblin Green", hex: "63B521" },
  { range: "Old Citadel", name: "Golden Yellow", hex: "FFCE00" },
  { range: "Old Citadel", name: "Graveyard Earth", hex: "655138" },
  { range: "Old Citadel", name: "Gretchin Green", hex: "5D6732" },
  { range: "Old Citadel", name: "Gryphonne Sepia Wash", hex: "843910" },
  { range: "Old Citadel", name: "Hawk Turquoise", hex: "006B5A" },
  { range: "Old Citadel", name: "Hormagaunt Purple", hex: "4F566C" },
  { range: "Old Citadel", name: "Ice Blue", hex: "6B9CCE" },
  { range: "Old Citadel", name: "Imperial Purple", hex: "562F7E" },
  { range: "Old Citadel", name: "Iyanden Darksun", hex: "9C8A53" },
  { range: "Old Citadel", name: "Jade Green", hex: "069B7D" },
  { range: "Old Citadel", name: "Khemri Brown", hex: "705E48" },
  { range: "Old Citadel", name: "Knarloc Green", hex: "434F38" },
  { range: "Old Citadel", name: "Kommando Khaki", hex: "9E915C" },
  { range: "Old Citadel", name: "Leprous Brown", hex: "D88E2D" },
  { range: "Old Citadel", name: "Leviathan Purple Wash", hex: "842994" },
  { range: "Old Citadel", name: "Liche Purple", hex: "5A005A" },
  { range: "Old Citadel", name: "Lightning Bolt Blue", hex: "8BB9DD" },
  { range: "Old Citadel", name: "Macharius Solar Orange", hex: "EE3823" },
  { range: "Old Citadel", name: "Magenta Ink", hex: "513D3C" },
  { range: "Old Citadel", name: "Mechrite Red", hex: "991115" },
  { range: "Old Citadel", name: "Midnight Blue", hex: "000031" },
  { range: "Old Citadel", name: "Mithril Silver", hex: "B5B5BD" },
  { range: "Old Citadel", name: "Mordian Blue", hex: "2D567C" },
  { range: "Old Citadel", name: "Nauseating Blue", hex: "412A7A" },
  { range: "Old Citadel", name: "Ogryn Flesh Wash", hex: "CE8C42" },
  { range: "Old Citadel", name: "Orkhide Shade", hex: "384E49" },
  { range: "Old Citadel", name: "Pallid Flesh", hex: "EEC8C7" },
  { range: "Old Citadel", name: "Purple Ink", hex: "842994" },
  { range: "Old Citadel", name: "Red Gore", hex: "940008" },
  { range: "Old Citadel", name: "Regal Blue", hex: "08085A" },
  { range: "Old Citadel", name: "Rotting Flesh", hex: "849B63" },
  { range: "Old Citadel", name: "Scab Red", hex: "6A0002" },
  { range: "Old Citadel", name: "Scaly Green", hex: "026B67" },
  { range: "Old Citadel", name: "Scorched Brown", hex: "390008" },
  { range: "Old Citadel", name: "Scorpion Green", hex: "A5D610" },
  { range: "Old Citadel", name: "Shadow Grey", hex: "4E5067" },
  { range: "Old Citadel", name: "Shining Gold", hex: "CCCC33" },
  { range: "Old Citadel", name: "Skull White", hex: "FFFFFF" },
  { range: "Old Citadel", name: "Smelly Primer", hex: "FFFFFF" },
  { range: "Old Citadel", name: "Snakebite Leather", hex: "9C6B08" },
  { range: "Old Citadel", name: "Snot Green", hex: "106B21" },
  { range: "Old Citadel", name: "Space Wolves Grey", hex: "CEDEE7" },
  { range: "Old Citadel", name: "Storm Blue", hex: "27357E" },
  { range: "Old Citadel", name: "Sunburst Yellow", hex: "FFE700" },
  { range: "Old Citadel", name: "Tallarn Flesh", hex: "8D736C" },
  { range: "Old Citadel", name: "Tanned Flesh", hex: "A95C3E" },
  { range: "Old Citadel", name: "Tausept Ochre", hex: "976F3C" },
  { range: "Old Citadel", name: "Tentacle Pink", hex: "EF9CB5" },
  { range: "Old Citadel", name: "Terracotta", hex: "793721" },
  { range: "Old Citadel", name: "Tin Bitz", hex: "393121" },
  { range: "Old Citadel", name: "Ultramarine Blue", hex: "29397B" },
  { range: "Old Citadel", name: "Vermin Brown", hex: "843910" },
  { range: "Old Citadel", name: "Vile Green", hex: "82C59C" },
  { range: "Old Citadel", name: "Vomit Brown", hex: "DE9408" },
  { range: "Old Citadel", name: "Warlock Purple", hex: "9C004A" },
  { range: "Privateer Press P3", name: "Arcane Blue", hex: "7ACFD9" },
  { range: "Privateer Press P3", name: "Bad Bruise", hex: "412A7A" },
  { range: "Privateer Press P3", name: "Bastion Grey", hex: "777965" },
  { range: "Privateer Press P3", name: "Beaten Purple", hex: "552A72" },
  { range: "Privateer Press P3", name: "Bloodtracker Brown", hex: "A66A28" },
  { range: "Privateer Press P3", name: "Brass Balls 2", hex: "E7BD42" },
  { range: "Privateer Press P3", name: "Carnal Pink", hex: "FAE2EC" },
  { range: "Privateer Press P3", name: "Cold Steel", hex: "7B737B" },
  { range: "Privateer Press P3", name: "Cygnar Blue Highlight", hex: "1F75BB" },
  { range: "Privateer Press P3", name: "Deathless Metal", hex: "393121" },
  { range: "Privateer Press P3", name: "Eldritch", hex: "069B7D" },
  { range: "Privateer Press P3", name: "Frostbite", hex: "E7F2F8" },
  { range: "Privateer Press P3", name: "Gnarls Green 2", hex: "005221" },
  { range: "Privateer Press P3", name: "Great Coat Grey", hex: "4D5861" },
  { range: "Privateer Press P3", name: "Gun Corps Brown", hex: "937D48" },
  { range: "Privateer Press P3", name: "Hammerfall Khaki", hex: "C8BF98" },
  { range: "Privateer Press P3", name: "Heartfire", hex: "F6B046" },
  { range: "Privateer Press P3", name: "Ioson Green", hex: "106B21" },
  { range: "Privateer Press P3", name: "Jack Bone", hex: "D6D4AA" },
  { range: "Privateer Press P3", name: "Khardic Flesh", hex: "CB7B5B" },
  { range: "Privateer Press P3", name: "Menoth White Base", hex: "EFEFBB" },
  { range: "Privateer Press P3", name: "Menoth White Highlight", hex: "F3F4DE" },
  { range: "Privateer Press P3", name: "Meredius Blue", hex: "00B0B9" },
  { range: "Privateer Press P3", name: "Moldy Ochre", hex: "DDB43E" },
  { range: "Privateer Press P3", name: "Molten Bronze", hex: "9C5221" },
  { range: "Privateer Press P3", name: "Morrow White", hex: "FEFBFD" },
  { range: "Privateer Press P3", name: "Murderous Magenta", hex: "A81F5E" },
  { range: "Privateer Press P3", name: "Necrotite Green", hex: "7FC348" },
  { range: "Privateer Press P3", name: "Pig Iron", hex: "393939" },
  { range: "Privateer Press P3", name: "Quicksilver", hex: "B5B5BD" },
  { range: "Privateer Press P3", name: "Rucksack Tan", hex: "B4973F" },
  { range: "Privateer Press P3", name: "Ryn Flesh", hex: "FAE3D1" },
  { range: "Privateer Press P3", name: "Solid Gold", hex: "CCCC33" },
  { range: "Privateer Press P3", name: "Sulferic Yellow", hex: "9C8A53" },
  { range: "Privateer Press P3", name: "Thamar Black", hex: "040707" },
  { range: "Privateer Press P3", name: "Umbral Umber", hex: "260801" },
  { range: "Privateer Press P3", name: "Underbelly Blue", hex: "C0D4DA" },
  { range: "Rackham", name: "Abyssal Blue (3)", hex: "000031" },
  { range: "Rackham", name: "Accursed Black (2)", hex: "000000" },
  { range: "Rackham", name: "Antique Green (13)", hex: "82C59C" },
  { range: "Rackham", name: "Arcavia Red (35)", hex: "6A0002" },
  { range: "Rackham", name: "Avagddu Green (17)", hex: "106B21" },
  { range: "Rackham", name: "Beastly Flesh (21)", hex: "630808" },
  { range: "Rackham", name: "Celestial Pink (46)", hex: "9C004A" },
  { range: "Rackham", name: "Chasm Green (16)", hex: "63B521" },
  { range: "Rackham", name: "Chitin Green (19)", hex: "026B67" },
  { range: "Rackham", name: "Craggy Skin (30)", hex: "F7BD7B" },
  { range: "Rackham", name: "Dead Flesh (11)", hex: "849B63" },
  { range: "Rackham", name: "Diisha Green (18)", hex: "005221" },
  { range: "Rackham", name: "Dirty Leather (20)", hex: "390008" },
  { range: "Rackham", name: "Divine Purple (6)", hex: "5A005A" },
  { range: "Rackham", name: "Ephren Blue (4)", hex: "31639C" },
  { range: "Rackham", name: "Eternal White (1)", hex: "FFFFFF" },
  { range: "Rackham", name: "Forgotten Gold (25)", hex: "C68400" },
  { range: "Rackham", name: "Friend Flesh (33)", hex: "EF9CB5" },
  { range: "Rackham", name: "Fusion Red (37)", hex: "F46C2E" },
  { range: "Rackham", name: "Glacier Blue (9)", hex: "6B9CCE" },
  { range: "Rackham", name: "Gray of Darkness (45)", hex: "999999" },
  { range: "Rackham", name: "Kalliene Yellow (23)", hex: "9C6B08" },
  { range: "Rackham", name: "Lahn Yellow (40)", hex: "FFE700" },
  { range: "Rackham", name: "Merin\'s Fire (38)", hex: "FF8552" },
  { range: "Rackham", name: "Migol Blue (5)", hex: "27357E" },
  { range: "Rackham", name: "Mystic Green (15)", hex: "A9D171" },
  { range: "Rackham", name: "Natural Leather (34)", hex: "940008" },
  { range: "Rackham", name: "Pearly Flesh (31)", hex: "EEC8C7" },
  { range: "Rackham", name: "Polished Silver (49)", hex: "B5B5BD" },
  { range: "Rackham", name: "Precious Blue (12)", hex: "006B5A" },
  { range: "Rackham", name: "Quithayran Green (14)", hex: "A5D610" },
  { range: "Rackham", name: "Rackham Red (36)", hex: "C21920" },
  { range: "Rackham", name: "Royal Yellow (39)", hex: "FFCE00" },
  { range: "Rackham", name: "Sacred Blue 2 (8)", hex: "8BB9DD" },
  { range: "Rackham", name: "Sharp Gray (43)", hex: "B5B5B5" },
  { range: "Rackham", name: "Soil of Avagddu (22)", hex: "663300" },
  { range: "Rackham", name: "Syhar Soil (24)", hex: "843910" },
  { range: "Rackham", name: "Tanned Skin (29)", hex: "DE9408" },
  { range: "Rackham", name: "Wildcat Gray 2 (42)", hex: "EFD9A8" },
  { range: "Rackham", name: "Wizard Blue 2 (7)", hex: "29397B" },
  { range: "Reaper Master", name: "Ancient Bronze (9049)", hex: "9C5221" },
  { range: "Reaper Master", name: "Antique Gold (9050)", hex: "E7BD42" },
  { range: "Reaper Master", name: "Antique Rose (9139)", hex: "A95C3E" },
  { range: "Reaper Master", name: "Armor Wash", hex: "000000" },
  { range: "Reaper Master", name: "Breonne Blue (9055)", hex: "2D567C" },
  { range: "Reaper Master", name: "Brilliant Blue (9116)", hex: "08085A" },
  { range: "Reaper Master", name: "Brush-on Primer (9108)", hex: "FFFFFF" },
  { range: "Reaper Master", name: "Burnt Orange 2 (9111)", hex: "F7944A" },
  { range: "Reaper Master", name: "Camouflage Green 2 (9177)", hex: "A5A542" },
  { range: "Reaper Master", name: "Carnage Red (9135)", hex: "940008" },
  { range: "Reaper Master", name: "Chestnut Brown (9071)", hex: "630808" },
  { range: "Reaper Master", name: "Chestnut Brown 2 (9071)", hex: "843910" },
  { range: "Reaper Master", name: "Chestnut Gold (9073)", hex: "9C6B08" },
  { range: "Reaper Master", name: "Clear Green (9096)", hex: "106B21" },
  { range: "Reaper Master", name: "Clear Plum (9132)", hex: "5A005A" },
  { range: "Reaper Master", name: "Clear Purple (9099)", hex: "412A7A" },
  { range: "Reaper Master", name: "Clear Red (9094)", hex: "C21920" },
  { range: "Reaper Master", name: "Clear Viridian (9131)", hex: "026B67" },
  { range: "Reaper Master", name: "Clear Yellow (9095)", hex: "FFF700" },
  { range: "Reaper Master", name: "Clotted Red (9134)", hex: "991115" },
  { range: "Reaper Master", name: "Coppery Orange (9102)", hex: "73372D" },
  { range: "Reaper Master", name: "Cyan Blue 2 (9117)", hex: "31639C" },
  { range: "Reaper Master", name: "Dark Highlight (9042)", hex: "6D5044" },
  { range: "Reaper Master", name: "Deep Amethyst (9079)", hex: "562F7E" },
  { range: "Reaper Master", name: "Deep Red (9002)", hex: "6A0002" },
  { range: "Reaper Master", name: "Faded Khaki (9129)", hex: "9C8855" },
  { range: "Reaper Master", name: "Field Green 2 (9167)", hex: "63B521" },
  { range: "Reaper Master", name: "Fire Orange (9006)", hex: "FF8552" },
  { range: "Reaper Master", name: "Ghost White (9063)", hex: "C3C6CD" },
  { range: "Reaper Master", name: "Green Ochre (9128)", hex: "9C8A53" },
  { range: "Reaper Master", name: "Half Orc Highlight (9204)", hex: "976F3C" },
  { range: "Reaper Master", name: "Honed Steel (9053)", hex: "7B737B" },
  { range: "Reaper Master", name: "Intense Brown (9138)", hex: "663300" },
  { range: "Reaper Master", name: "Jungle Moss (9082)", hex: "384E49" },
  { range: "Reaper Master", name: "Leather Brown (9030)", hex: "8D736C" },
  { range: "Reaper Master", name: "Marigold Yellow (9007)", hex: "FFCE00" },
  { range: "Reaper Master", name: "Marine Teal (9077)", hex: "006B5A" },
  { range: "Reaper Master", name: "Military Green 2", hex: "7C8286" },
  { range: "Reaper Master", name: "Muddy Brown (9028)", hex: "390008" },
  { range: "Reaper Master", name: "Muddy Olive (9034)", hex: "455440" },
  { range: "Reaper Master", name: "Muddy Wash", hex: "393121" },
  { range: "Reaper Master", name: "New Gold (9051)", hex: "CCCC33" },
  { range: "Reaper Master", name: "Nightshade Purple (9022)", hex: "4F566C" },
  { range: "Reaper Master", name: "Olive Drab (9158)", hex: "434F38" },
  { range: "Reaper Master", name: "Pale Green (9012)", hex: "A5D610" },
  { range: "Reaper Master", name: "Pale Olive (9036)", hex: "849B63" },
  { range: "Reaper Master", name: "Pale Violet 2 (9027)", hex: "EF9CB5" },
  { range: "Reaper Master", name: "Pale Violet Red (9027)", hex: "9C004A" },
  { range: "Reaper Master", name: "Palomino Gold (9074)", hex: "C68400" },
  { range: "Reaper Master", name: "Phoenix Red (9005)", hex: "EE3823" },
  { range: "Reaper Master", name: "Pine Green 2 (9010)", hex: "005221" },
  { range: "Reaper Master", name: "Polished Silver (9054)", hex: "B5B5BD" },
  { range: "Reaper Master", name: "Pure Black (9037)", hex: "000000" },
  { range: "Reaper Master", name: "Pure Black (9103) 2", hex: "4D4A4A" },
  { range: "Reaper Master", name: "Pure White (9039)", hex: "FFFFFF" },
  { range: "Reaper Master", name: "Rainy Grey (9038)", hex: "999999" },
  { range: "Reaper Master", name: "Reptilian Greens Triad 2 (9184/9185/9186)", hex: "069B7D" },
  { range: "Reaper Master", name: "Ritterlich Blue 2 (9115)", hex: "27357E" },
  { range: "Reaper Master", name: "Rosy Highlight (9069)", hex: "EEC8C7" },
  { range: "Reaper Master", name: "Rosy Highlight 2 (9069)", hex: "F7BD7B" },
  { range: "Reaper Master", name: "Rosy Skin (9068)", hex: "F78C5A" },
  { range: "Reaper Master", name: "Saffron Sunset 2 (9182)", hex: "D88E2D" },
  { range: "Reaper Master", name: "Scorched Metal (9125)", hex: "393121" },
  { range: "Reaper Master", name: "Shadowed Steel (9052)", hex: "393939" },
  { range: "Reaper Master", name: "Sky Blue 2 (9018)", hex: "8BB9DD" },
  { range: "Reaper Master", name: "Snow Shadow (9021)", hex: "CEDEE7" },
  { range: "Reaper Master", name: "Spring Green 2 (9146)", hex: "A9D171" },
  { range: "Reaper Master", name: "Sun Yellow (9008)", hex: "FFE700" },
  { range: "Reaper Master", name: "Tanned Leather (9031)", hex: "DE9408" },
  { range: "Reaper Master", name: "Tarnished Brass 2 (9198)", hex: "735A21" },
  { range: "Reaper Master", name: "Terran Khaki (9122)", hex: "9E915C" },
  { range: "Reaper Master", name: "Twilight Blue (9020)", hex: "4E5067" },
  { range: "Reaper Master", name: "Ultramarine Highlight 2 (9189)", hex: "29397B" },
  { range: "Reaper Master", name: "Ultramarine Shadow (9187)", hex: "000031" },
  { range: "Reaper Master", name: "Uniform Brown (9127)", hex: "655138" },
  { range: "Reaper Master", name: "Vampiric Shadow (9274)", hex: "B9ADA1" },
  { range: "Reaper Master", name: "Weathered Stone (9087)", hex: "B5B5B5" },
  { range: "Reaper Master", name: "Woodstain Brown (9160)", hex: "705E48" },
  { range: "Reaper Master", name: "Worn Olive (9159)", hex: "5D6732" },
  { range: "Reaper Master", name: "Yellowed Bone (9143)", hex: "EFD9A8" },
  { range: "Scale 75", name: "Adriatic Blue Matt", hex: "006B5A" },
  { range: "Scale 75", name: "Antares Red", hex: "C21920" },
  { range: "Scale 75", name: "Anthartic Grey Matt", hex: "4D4A4A" },
  { range: "Scale 75", name: "Arabic Shadow Matt", hex: "705E48" },
  { range: "Scale 75", name: "Ardennes Green Matt", hex: "A5A542" },
  { range: "Scale 75", name: "Artic Blue Matt", hex: "999999" },
  { range: "Scale 75", name: "Bering Blue Matt", hex: "CEDEE7" },
  { range: "Scale 75", name: "Black", hex: "384E49" },
  { range: "Scale 75", name: "Black Leather Matt", hex: "390008" },
  { range: "Scale 75", name: "Boreal Green Matt", hex: "455440" },
  { range: "Scale 75", name: "Deep Red Matt", hex: "6A0002" },
  { range: "Scale 75", name: "Dungeon Stone Grey", hex: "7C8286" },
  { range: "Scale 75", name: "Dwarven Gold", hex: "E7BD42" },
  { range: "Scale 75", name: "Elven Gold", hex: "CCCC33" },
  { range: "Scale 75", name: "Fuchsia Matt", hex: "9C004A" },
  { range: "Scale 75", name: "Gobi Brown Matt", hex: "655138" },
  { range: "Scale 75", name: "Golden Skin Matt", hex: "EFD9A8" },
  { range: "Scale 75", name: "Indian Shadow", hex: "940008" },
  { range: "Scale 75", name: "Irati Green", hex: "106B21" },
  { range: "Scale 75", name: "Iroko Matt", hex: "C68400" },
  { range: "Scale 75", name: "Kalahari Orange Matt", hex: "A95C3E" },
  { range: "Scale 75", name: "Mars Orange Matt", hex: "843910" },
  { range: "Scale 75", name: "Nacar Matt", hex: "B5B5B5" },
  { range: "Scale 75", name: "Navy Blue Matt", hex: "2D567C" },
  { range: "Scale 75", name: "Necro Gold", hex: "393121" },
  { range: "Scale 75", name: "Neo Pink", hex: "F5AECC" },
  { range: "Scale 75", name: "Pale Skin Matt", hex: "EEC8C7" },
  { range: "Scale 75", name: "Petroleum Grey", hex: "393939" },
  { range: "Scale 75", name: "Sahara Yellow Matt", hex: "9C8855" },
  { range: "Scale 75", name: "Sky Blue", hex: "6B9CCE" },
  { range: "Scale 75", name: "Spring Green", hex: "A5D610" },
  { range: "Scale 75", name: "Thar Brown Matt", hex: "9E915C" },
  { range: "Scale 75", name: "Viking Gold", hex: "735A21" },
  { range: "Scale 75", name: "Violet Blue Matt", hex: "4F566C" },
  { range: "Scale 75", name: "White Matt", hex: "FFFFFF" },
  { range: "Scale 75", name: "White Sands Matt", hex: "F0F1CE" },
  { range: "Two Thin Coats", name: "Abyss Blue", hex: "08085A" },
  { range: "Two Thin Coats", name: "Ancient Forest", hex: "5F463F" },
  { range: "Two Thin Coats", name: "Archaic Sepia Wash", hex: "843910" },
  { range: "Two Thin Coats", name: "Ashen Grey", hex: "484B4E" },
  { range: "Two Thin Coats", name: "Asmodeus Red", hex: "6A0002" },
  { range: "Two Thin Coats", name: "Barbarian Brawn", hex: "A95C3E" },
  { range: "Two Thin Coats", name: "Battle Axe Brass", hex: "735A21" },
  { range: "Two Thin Coats", name: "Battle Mud Wash", hex: "393121" },
  { range: "Two Thin Coats", name: "Berserker Red", hex: "620104" },
  { range: "Two Thin Coats", name: "Boar Hide", hex: "630808" },
  { range: "Two Thin Coats", name: "Carcharodon Grey", hex: "B5B5B5" },
  { range: "Two Thin Coats", name: "Celestial Blue", hex: "A4BAD2" },
  { range: "Two Thin Coats", name: "Cold Corpse Blue", hex: "4E5067" },
  { range: "Two Thin Coats", name: "Cuirass Leather", hex: "390008" },
  { range: "Two Thin Coats", name: "Cursed Blue", hex: "00708A" },
  { range: "Two Thin Coats", name: "Dark Sun Yellow", hex: "9C8A53" },
  { range: "Two Thin Coats", name: "Death Reaper", hex: "171314" },
  { range: "Two Thin Coats", name: "Demon Red", hex: "C21920" },
  { range: "Two Thin Coats", name: "Doom Death Black", hex: "000000" },
  { range: "Two Thin Coats", name: "Dragon Fang", hex: "9E915C" },
  { range: "Two Thin Coats", name: "Dread Red", hex: "4B213C" },
  { range: "Two Thin Coats", name: "Dry Rust Brown", hex: "843910" },
  { range: "Two Thin Coats", name: "Dust Bowl", hex: "655138" },
  { range: "Two Thin Coats", name: "Dwarven Skin", hex: "8D736C" },
  { range: "Two Thin Coats", name: "Eidolon Grey", hex: "45413B" },
  { range: "Two Thin Coats", name: "Elven Skin", hex: "EEC8C7" },
  { range: "Two Thin Coats", name: "Emerald Green", hex: "106B21" },
  { range: "Two Thin Coats", name: "Ethereal Green", hex: "A5D610" },
  { range: "Two Thin Coats", name: "Evil Eye Red", hex: "940008" },
  { range: "Two Thin Coats", name: "Fanatic Orange", hex: "F46C2E" },
  { range: "Two Thin Coats", name: "Flesh Wash", hex: "CE8C42" },
  { range: "Two Thin Coats", name: "Fury Green", hex: "455440" },
  { range: "Two Thin Coats", name: "Ghoul Green", hex: "82C59C" },
  { range: "Two Thin Coats", name: "Goblinoid Green", hex: "63B521" },
  { range: "Two Thin Coats", name: "Gravestone Blue", hex: "CEDEE7" },
  { range: "Two Thin Coats", name: "Green Beret", hex: "628026" },
  { range: "Two Thin Coats", name: "Griffon Claw", hex: "B9ADA1" },
  { range: "Two Thin Coats", name: "Gung-Ho Green", hex: "434F38" },
  { range: "Two Thin Coats", name: "Gyzmo Fur", hex: "793721" },
  { range: "Two Thin Coats", name: "Hellion Red Wash", hex: "630808" },
  { range: "Two Thin Coats", name: "Hot Pink", hex: "EF9CB5" },
  { range: "Two Thin Coats", name: "Hydra Green", hex: "082E32" },
  { range: "Two Thin Coats", name: "Ivory Tusk", hex: "CDCEBE" },
  { range: "Two Thin Coats", name: "Jade Green", hex: "069B7D" },
  { range: "Two Thin Coats", name: "Kobold Grey", hex: "BFBD82" },
  { range: "Two Thin Coats", name: "Leviathan Blue", hex: "4C78AF" },
  { range: "Two Thin Coats", name: "Magi Purple Wash", hex: "842994" },
  { range: "Two Thin Coats", name: "Manticore Ochre", hex: "DE9408" },
  { range: "Two Thin Coats", name: "Marine Blue", hex: "2D567C" },
  { range: "Two Thin Coats", name: "Necrosis Green Wash", hex: "8B8B66" },
  { range: "Two Thin Coats", name: "Noble Steed Brown", hex: "663300" },
  { range: "Two Thin Coats", name: "Oblivion Black Wash", hex: "000000" },
  { range: "Two Thin Coats", name: "Orange Flare", hex: "FF8552" },
  { range: "Two Thin Coats", name: "Orc Flesh Wash", hex: "547757" },
  { range: "Two Thin Coats", name: "Orc Hide", hex: "384E49" },
  { range: "Two Thin Coats", name: "Ray Gun Glow", hex: "59C1CE" },
  { range: "Two Thin Coats", name: "Rodent Grey", hex: "4D4A4A" },
  { range: "Two Thin Coats", name: "Royal Cloak", hex: "451636" },
  { range: "Two Thin Coats", name: "Sanguine Scarlet", hex: "991115" },
  { range: "Two Thin Coats", name: "Scorched Earth", hex: "2B2A24" },
  { range: "Two Thin Coats", name: "Sentient Turquoise", hex: "00506F" },
  { range: "Two Thin Coats", name: "Sir Coates Silver", hex: "393939" },
  { range: "Two Thin Coats", name: "Skeleton Legion", hex: "EFD9A8" },
  { range: "Two Thin Coats", name: "Skulker Yellow", hex: "FFCE00" },
  { range: "Two Thin Coats", name: "Sword Hilt Burgundy", hex: "9C004A" },
  { range: "Two Thin Coats", name: "Tempest Blue Wash", hex: "273E51" },
  { range: "Two Thin Coats", name: "Temple Stone", hex: "9B8C7B" },
  { range: "Two Thin Coats", name: "Vampire Fang", hex: "F0F1CE" },
  { range: "Two Thin Coats", name: "Wasteland Brown", hex: "705E48" },
  { range: "Two Thin Coats", name: "White Star", hex: "FFFFFF" },
  { range: "Two Thin Coats", name: "Witching Hour Blue", hex: "31639C" },
  { range: "Two Thin Coats", name: "Wizard Grey", hex: "999999" },
  { range: "Two Thin Coats", name: "Wyvern Green", hex: "005221" },
  { range: "Two Thin Coats", name: "Yellow Flame", hex: "FFE700" },
  { range: "Vallejo Game Color", name: "Bad Moon Yellow (005)", hex: "FFF700" },
  { range: "Vallejo Game Color", name: "Beasty Brown (043)", hex: "55432D" },
  { range: "Vallejo Game Color", name: "Black Ink (94)", hex: "000000" },
  { range: "Vallejo Game Color", name: "Black Wash (73201)", hex: "000000" },
  { range: "Vallejo Game Color", name: "Bloody Red (010)", hex: "BF282E" },
  { range: "Vallejo Game Color", name: "Blue Shade Wash (73207)", hex: "273E51" },
  { range: "Vallejo Game Color", name: "Bonewhite (034)", hex: "E8BE86" },
  { range: "Vallejo Game Color", name: "Brassy Brass (058)", hex: "735A21" },
  { range: "Vallejo Game Color", name: "Bright Bronze (057)", hex: "9C5221" },
  { range: "Vallejo Game Color", name: "Bronze Flesh (036)", hex: "F7944A" },
  { range: "Vallejo Game Color", name: "Camouflage Green (031)", hex: "A5A542" },
  { range: "Vallejo Game Color", name: "Cayman Green (067)", hex: "285648" },
  { range: "Vallejo Game Color", name: "Chain Mail (053)", hex: "7B737B" },
  { range: "Vallejo Game Color", name: "Chaos Black / Black (051)", hex: "000000" },
  { range: "Vallejo Game Color", name: "Charred Brown (045)", hex: "39343B" },
  { range: "Vallejo Game Color", name: "Cobra Leather / Leather Brown (040)", hex: "9C6B08" },
  { range: "Vallejo Game Color", name: "Cold Grey (050)", hex: "54646D" },
  { range: "Vallejo Game Color", name: "Dark Fleshtone (044)", hex: "4F2B26" },
  { range: "Vallejo Game Color", name: "Dark Green (028)", hex: "083C2A" },
  { range: "Vallejo Game Color", name: "Dead Flesh (035)", hex: "BCB686" },
  { range: "Vallejo Game Color", name: "Dead White (001)", hex: "FFFFFF" },
  { range: "Vallejo Game Color", name: "Desert Yellow (063)", hex: "8E7845" },
  { range: "Vallejo Game Color", name: "Dwarf Skin (041)", hex: "CC7C67" },
  { range: "Vallejo Game Color", name: "Earth (062)", hex: "6F563D" },
  { range: "Vallejo Game Color", name: "Electric Blue (023)", hex: "008CBF" },
  { range: "Vallejo Game Color", name: "Elf Skintone (004)", hex: "F8A070" },
  { range: "Vallejo Game Color", name: "Falcon Turquoise (024)", hex: "006B5A" },
  { range: "Vallejo Game Color", name: "Filthy Brown (037)", hex: "F58D2B" },
  { range: "Vallejo Game Color", name: "Fleshtone Shade Wash (73204)", hex: "CE8C42" },
  { range: "Vallejo Game Color", name: "Foul Green (025)", hex: "239378" },
  { range: "Vallejo Game Color", name: "Ghost Grey (046)", hex: "A7C5DB" },
  { range: "Vallejo Game Color", name: "Glorious Gold (056)", hex: "E7BD42" },
  { range: "Vallejo Game Color", name: "Goblin Green (030)", hex: "23743C" },
  { range: "Vallejo Game Color", name: "Gold Yellow (007)", hex: "FDB318" },
  { range: "Vallejo Game Color", name: "Gory Red (011)", hex: "810504" },
  { range: "Vallejo Game Color", name: "Green Ink (89)", hex: "108473" },
  { range: "Vallejo Game Color", name: "Green Wash", hex: "547757" },
  { range: "Vallejo Game Color", name: "Gunmetal / Gunmetal Metal (054)", hex: "393939" },
  { range: "Vallejo Game Color", name: "Hammered Copper (059)", hex: "73372D" },
  { range: "Vallejo Game Color", name: "Heavy Blackgreen (147)", hex: "18433D" },
  { range: "Vallejo Game Color", name: "Heavy Blue (143)", hex: "29556D" },
  { range: "Vallejo Game Color", name: "Heavy Bluegrey (144)", hex: "9CA7A7" },
  { range: "Vallejo Game Color", name: "Heavy Brown (153)", hex: "705D41" },
  { range: "Vallejo Game Color", name: "Heavy Charcoal (155)", hex: "1C2E2E" },
  { range: "Vallejo Game Color", name: "Heavy Goldbrown (151)", hex: "BA8636" },
  { range: "Vallejo Game Color", name: "Heavy Green (146)", hex: "566840" },
  { range: "Vallejo Game Color", name: "Heavy Grey 2", hex: "7C8286" },
  { range: "Vallejo Game Color", name: "Heavy Khaki (149)", hex: "9D965D" },
  { range: "Vallejo Game Color", name: "Heavy Ochre (150)", hex: "A87536" },
  { range: "Vallejo Game Color", name: "Heavy Orange (152)", hex: "EE5527" },
  { range: "Vallejo Game Color", name: "Heavy Red (141)", hex: "943238" },
  { range: "Vallejo Game Color", name: "Heavy Siena (154)", hex: "6D5044" },
  { range: "Vallejo Game Color", name: "Heavy Skintone (140)", hex: "AA7B62" },
  { range: "Vallejo Game Color", name: "Heavy Violet (142)", hex: "4C2E65" },
  { range: "Vallejo Game Color", name: "Heavy Warmgrey 2 (148)", hex: "B9ADA1" },
  { range: "Vallejo Game Color", name: "Hexed Lichen (015)", hex: "34274D" },
  { range: "Vallejo Game Color", name: "Hot Orange (009)", hex: "E43027" },
  { range: "Vallejo Game Color", name: "Ice Blue (095)", hex: "6B9CCE" },
  { range: "Vallejo Game Color", name: "Imperial Blue (020)", hex: "08085A" },
  { range: "Vallejo Game Color", name: "Jade Green (026)", hex: "128379" },
  { range: "Vallejo Game Color", name: "Khaki (061)", hex: "8C806D" },
  { range: "Vallejo Game Color", name: "Livery Green (033)", hex: "9ECE65" },
  { range: "Vallejo Game Color", name: "Magic Blue (021)", hex: "024381" },
  { range: "Vallejo Game Color", name: "Mithril Silver / Silver (052)", hex: "B5B5BD" },
  { range: "Vallejo Game Color", name: "Night Blue (019)", hex: "19183F" },
  { range: "Vallejo Game Color", name: "Orange Fire (008)", hex: "F1652E" },
  { range: "Vallejo Game Color", name: "Pale Flesh (003)", hex: "F6BDB3" },
  { range: "Vallejo Game Color", name: "Pale Grey Shade Wash (73202)", hex: "842994" },
  { range: "Vallejo Game Color", name: "Parasite Brown (042)", hex: "B1481F" },
  { range: "Vallejo Game Color", name: "Plague Brown (039)", hex: "CC9B34" },
  { range: "Vallejo Game Color", name: "Polished Gold (055)", hex: "CCCC33" },
  { range: "Vallejo Game Color", name: "Red Shade Wash (73206)", hex: "630808" },
  { range: "Vallejo Game Color", name: "Royal Purple (016)", hex: "23264F" },
  { range: "Vallejo Game Color", name: "Scarlett Red (012)", hex: "6A0002" },
  { range: "Vallejo Game Color", name: "Scorpy Green (032)", hex: "A5D610" },
  { range: "Vallejo Game Color", name: "Scrofulous Brown (038)", hex: "D68030" },
  { range: "Vallejo Game Color", name: "Scurf/Scurvey Green (027)", hex: "026B67" },
  { range: "Vallejo Game Color", name: "Sepia Wash (73200)", hex: "843910" },
  { range: "Vallejo Game Color", name: "Sick Blue (017)", hex: "412A7A" },
  { range: "Vallejo Game Color", name: "Sick Green (029)", hex: "096638" },
  { range: "Vallejo Game Color", name: "Sombre Grey (048)", hex: "4C5C7D" },
  { range: "Vallejo Game Color", name: "Squid Pink (013)", hex: "DA7FB5" },
  { range: "Vallejo Game Color", name: "Stonewall Grey (049)", hex: "828E95" },
  { range: "Vallejo Game Color", name: "Stormy Blue (018)", hex: "27357E" },
  { range: "Vallejo Game Color", name: "Sunblast Yellow (006)", hex: "FFE700" },
  { range: "Vallejo Game Color", name: "Tan (066)", hex: "9F4746" },
  { range: "Vallejo Game Color", name: "Terracotta (065)", hex: "793721" },
  { range: "Vallejo Game Color", name: "Tinny Tin (060)", hex: "393121" },
  { range: "Vallejo Game Color", name: "Ultra Marine Blue (022)", hex: "373592" },
  { range: "Vallejo Game Color", name: "Umber Shade Wash (73203)", hex: "393121" },
  { range: "Vallejo Game Color", name: "Violet Ink (87)", hex: "842994" },
  { range: "Vallejo Game Color", name: "Warlord Purple (014)", hex: "7D1A44" },
  { range: "Vallejo Game Color", name: "White Primer (002)", hex: "FFFFFF" },
  { range: "Vallejo Game Color", name: "Wolf Grey (047)", hex: "90A2BC" },
  { range: "Vallejo Model Color", name: "Azure 2 (902)", hex: "6B9CCE" },
  { range: "Vallejo Model Color", name: "Basalt Grey (869)", hex: "576860" },
  { range: "Vallejo Model Color", name: "Beige Red 2", hex: "DE9408" },
  { range: "Vallejo Model Color", name: "Black (950)", hex: "252B31" },
  { range: "Vallejo Model Color", name: "Black Green (980)", hex: "19423E" },
  { range: "Vallejo Model Color", name: "Blue (925)", hex: "043667" },
  { range: "Vallejo Model Color", name: "Brass (801)", hex: "735A21" },
  { range: "Vallejo Model Color", name: "Bronze (998)", hex: "9C5221" },
  { range: "Vallejo Model Color", name: "Brown Rose", hex: "CF8774" },
  { range: "Vallejo Model Color", name: "Brown Sand", hex: "B08064" },
  { range: "Vallejo Model Color", name: "Brown Sand (876)", hex: "B08064" },
  { range: "Vallejo Model Color", name: "Buff (976)", hex: "D2CA9F" },
  { range: "Vallejo Model Color", name: "Burnt Umber (941)", hex: "665148" },
  { range: "Vallejo Model Color", name: "Carmine Red (908)", hex: "B73035" },
  { range: "Vallejo Model Color", name: "Cavalry Brown (982)", hex: "853F3D" },
  { range: "Vallejo Model Color", name: "Copper (999)", hex: "73372D" },
  { range: "Vallejo Model Color", name: "Dark Blue (930)", hex: "0D5A86" },
  { range: "Vallejo Model Color", name: "Dark Flesh (927)", hex: "D9A262" },
  { range: "Vallejo Model Color", name: "Dark Prussian Blue", hex: "192C43" },
  { range: "Vallejo Model Color", name: "Dark Sea Blue", hex: "2A4048" },
  { range: "Vallejo Model Color", name: "Dark Sea Blue (898)", hex: "2A4048" },
  { range: "Vallejo Model Color", name: "Dark Yellow (978)", hex: "9D9059" },
  { range: "Vallejo Model Color", name: "Deep Green (970)", hex: "0A6B48" },
  { range: "Vallejo Model Color", name: "Emerald (838)", hex: "00906A" },
  { range: "Vallejo Model Color", name: "Flat Aluminum (993)", hex: "C3C6CD" },
  { range: "Vallejo Model Color", name: "Flat Brown (984)", hex: "764841" },
  { range: "Vallejo Model Color", name: "Flat Flesh (955)", hex: "D8A977" },
  { range: "Vallejo Model Color", name: "Flat Yellow", hex: "FFCD25" },
  { range: "Vallejo Model Color", name: "Foundation White (919)", hex: "FFFFFF" },
  { range: "Vallejo Model Color", name: "G. Cam. Beige (821)", hex: "9E915C" },
  { range: "Vallejo Model Color", name: "German Cam. Beige WWII (821)", hex: "9B8C7B" },
  { range: "Vallejo Model Color", name: "German Grey (995)", hex: "192F30" },
  { range: "Vallejo Model Color", name: "German Orange (805)", hex: "F05426" },
  { range: "Vallejo Model Color", name: "Gold (996)", hex: "E7BD42" },
  { range: "Vallejo Model Color", name: "Gold Brown (877)", hex: "BA8636" },
  { range: "Vallejo Model Color", name: "Goldbrown (877)", hex: "BA8636" },
  { range: "Vallejo Model Color", name: "Golden Yellow (948)", hex: "F7C65E" },
  { range: "Vallejo Model Color", name: "Green Brown", hex: "8D7B55" },
  { range: "Vallejo Model Color", name: "Green Sky", hex: "59AD84" },
  { range: "Vallejo Model Color", name: "Gunmetal Grey (863)", hex: "393939" },
  { range: "Vallejo Model Color", name: "Intermediate Green (891)", hex: "49944F" },
  { range: "Vallejo Model Color", name: "Ivory (918)", hex: "EFF1D9" },
  { range: "Vallejo Model Color", name: "Lemon Yellow (952)", hex: "FEF10E" },
  { range: "Vallejo Model Color", name: "Light Flesh (928)", hex: "FEEDD0" },
  { range: "Vallejo Model Color", name: "Light Green (942)", hex: "00A850" },
  { range: "Vallejo Model Color", name: "Light Orange (911)", hex: "F68627" },
  { range: "Vallejo Model Color", name: "Light Turquoise (840)", hex: "0094A5" },
  { range: "Vallejo Model Color", name: "Luftwaffe Ca. Green (823)", hex: "434F38" },
  { range: "Vallejo Model Color", name: "Magenta (945)", hex: "A92A56" },
  { range: "Vallejo Model Color", name: "Mahogany Brown (846)", hex: "804B47" },
  { range: "Vallejo Model Color", name: "Natural Steel (864)", hex: "7B737B" },
  { range: "Vallejo Model Color", name: "Ochre Brown (856)", hex: "A77237" },
  { range: "Vallejo Model Color", name: "Old Gold (878)", hex: "CCCC33" },
  { range: "Vallejo Model Color", name: "Olive Green (967)", hex: "6A8B3A" },
  { range: "Vallejo Model Color", name: "Olive Grey (888)", hex: "39584F" },
  { range: "Vallejo Model Color", name: "Orange Brown (981)", hex: "B86F44" },
  { range: "Vallejo Model Color", name: "Oxford Blue (807)", hex: "3A465F" },
  { range: "Vallejo Model Color", name: "Pale Blue Grey (905)", hex: "96A5A9" },
  { range: "Vallejo Model Color", name: "Pale Grey Blue (907)", hex: "BACDD0" },
  { range: "Vallejo Model Color", name: "Pale Greyblue (907)", hex: "BACDD0" },
  { range: "Vallejo Model Color", name: "Park Green Flat (969)", hex: "008C5D" },
  { range: "Vallejo Model Color", name: "Pastel Green (885)", hex: "A4BB99" },
  { range: "Vallejo Model Color", name: "Pink (958)", hex: "D37497" },
  { range: "Vallejo Model Color", name: "Prussian Blue (965)", hex: "2A546E" },
  { range: "Vallejo Model Color", name: "Red (926)", hex: "91323A" },
  { range: "Vallejo Model Color", name: "Royal Purple (810)", hex: "4B2967" },
  { range: "Vallejo Model Color", name: "Russian Unif. (924)", hex: "7C8286" },
  { range: "Vallejo Model Color", name: "Russian Uniform WW2 (70.924)", hex: "606D53" },
  { range: "Vallejo Model Color", name: "Scarlet (817)", hex: "DA3630" },
  { range: "Vallejo Model Color", name: "Silver (997)", hex: "B5B5BD" },
  { range: "Vallejo Model Color", name: "Sky Blue (961)", hex: "86D6F7" },
  { range: "Vallejo Model Color", name: "US Field Drab", hex: "705D43" },
  { range: "Vallejo Model Color", name: "Ultramarine (839)", hex: "3B5DA7" },
  { range: "Vallejo Model Color", name: "Vermillion (909)", hex: "D22B2D" },
  { range: "Vallejo Model Color", name: "Violet (960)", hex: "4B2F65" },
  { range: "Vallejo Model Color", name: "Violet 2 (960)", hex: "412A7A" },
  { range: "Vallejo Model Color", name: "White (951)", hex: "FFFFFF" },
  { range: "Vallejo Model Color", name: "Yellow Green 2 (954)", hex: "A9D171" },
  { range: "Vallejo Model Color", name: "Yellow Ochre (913)", hex: "C19448" },
];
